# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['otk',
 'otk.asbp',
 'otk.asbp.test',
 'otk.draw2',
 'otk.rt1',
 'otk.rt1.test',
 'otk.rt2',
 'otk.rt2.test',
 'otk.rtm4',
 'otk.sdb',
 'otk.sdb.npscalar',
 'otk.sdb.numba',
 'otk.sdb.test',
 'otk.sdb.webex',
 'otk.test']

package_data = \
{'': ['*'],
 'otk': ['designs/README.md',
         'designs/README.md',
         'designs/README.md',
         'designs/README.md',
         'designs/US02084714-1.zmx',
         'designs/US02084714-1.zmx',
         'designs/US02084714-1.zmx',
         'designs/US02084714-1.zmx',
         'designs/US08934179-4.zmx',
         'designs/US08934179-4.zmx',
         'designs/US08934179-4.zmx',
         'designs/US08934179-4.zmx',
         'designs/aspheric_telecentric_lens.zmx',
         'designs/aspheric_telecentric_lens.zmx',
         'designs/aspheric_telecentric_lens.zmx',
         'designs/aspheric_telecentric_lens.zmx',
         'properties/agfs/Edmund-Optics-2018.agf',
         'properties/agfs/Edmund-Optics-2018.agf',
         'properties/agfs/Edmund-Optics-2018.agf',
         'properties/agfs/Edmund-Optics-2018.agf',
         'properties/agfs/Edmund-Optics-2018.agf',
         'properties/agfs/Edmund-Optics-2018.agf',
         'properties/agfs/Edmund-Optics-2018.agf',
         'properties/agfs/HOYA20200314_include_obsolete.agf',
         'properties/agfs/HOYA20200314_include_obsolete.agf',
         'properties/agfs/HOYA20200314_include_obsolete.agf',
         'properties/agfs/HOYA20200314_include_obsolete.agf',
         'properties/agfs/HOYA20200314_include_obsolete.agf',
         'properties/agfs/HOYA20200314_include_obsolete.agf',
         'properties/agfs/HOYA20200314_include_obsolete.agf',
         'properties/agfs/NIKON-HIKARI_201911.AGF',
         'properties/agfs/NIKON-HIKARI_201911.AGF',
         'properties/agfs/NIKON-HIKARI_201911.AGF',
         'properties/agfs/NIKON-HIKARI_201911.AGF',
         'properties/agfs/NIKON-HIKARI_201911.AGF',
         'properties/agfs/NIKON-HIKARI_201911.AGF',
         'properties/agfs/NIKON-HIKARI_201911.AGF',
         'properties/agfs/OHARA_200306_CATALOG.AGF',
         'properties/agfs/OHARA_200306_CATALOG.AGF',
         'properties/agfs/OHARA_200306_CATALOG.AGF',
         'properties/agfs/OHARA_200306_CATALOG.AGF',
         'properties/agfs/OHARA_200306_CATALOG.AGF',
         'properties/agfs/OHARA_200306_CATALOG.AGF',
         'properties/agfs/OHARA_200306_CATALOG.AGF',
         'properties/agfs/README.md',
         'properties/agfs/README.md',
         'properties/agfs/README.md',
         'properties/agfs/README.md',
         'properties/agfs/README.md',
         'properties/agfs/README.md',
         'properties/agfs/README.md',
         'properties/agfs/schottzemax-20180601.agf',
         'properties/agfs/schottzemax-20180601.agf',
         'properties/agfs/schottzemax-20180601.agf',
         'properties/agfs/schottzemax-20180601.agf',
         'properties/agfs/schottzemax-20180601.agf',
         'properties/agfs/schottzemax-20180601.agf',
         'properties/agfs/schottzemax-20180601.agf',
         'properties/agfs/sumita-opt-dl-data-20200511235805.agf',
         'properties/agfs/sumita-opt-dl-data-20200511235805.agf',
         'properties/agfs/sumita-opt-dl-data-20200511235805.agf',
         'properties/agfs/sumita-opt-dl-data-20200511235805.agf',
         'properties/agfs/sumita-opt-dl-data-20200511235805.agf',
         'properties/agfs/sumita-opt-dl-data-20200511235805.agf',
         'properties/agfs/sumita-opt-dl-data-20200511235805.agf',
         'properties/rii/*',
         'properties/rii/doc/*',
         'properties/rii/glass/ami/*',
         'properties/rii/glass/barberini/*',
         'properties/rii/glass/cdgm/*',
         'properties/rii/glass/corning/*',
         'properties/rii/glass/hikari/*',
         'properties/rii/glass/hoya/*',
         'properties/rii/glass/lightpath/*',
         'properties/rii/glass/lzos/*',
         'properties/rii/glass/misc/soda-lime/*',
         'properties/rii/glass/ohara/*',
         'properties/rii/glass/schott/*',
         'properties/rii/glass/schott/infrared/*',
         'properties/rii/glass/schott/inquiry/*',
         'properties/rii/glass/schott/misc/*',
         'properties/rii/glass/schott/obsolete/*',
         'properties/rii/glass/sumita/*',
         'properties/rii/glass/vitron/*',
         'properties/rii/main/Ag/*',
         'properties/rii/main/Ag3AsS3/*',
         'properties/rii/main/AgBr/*',
         'properties/rii/main/AgCl/*',
         'properties/rii/main/AgGaS2/*',
         'properties/rii/main/AgGaSe2/*',
         'properties/rii/main/Al/*',
         'properties/rii/main/Al2O3/*',
         'properties/rii/main/AlAs/*',
         'properties/rii/main/AlN/*',
         'properties/rii/main/AlSb/*',
         'properties/rii/main/Ar/*',
         'properties/rii/main/As2S3/*',
         'properties/rii/main/Au/*',
         'properties/rii/main/B/*',
         'properties/rii/main/B4C/*',
         'properties/rii/main/BP/*',
         'properties/rii/main/BaB2O4/*',
         'properties/rii/main/BaF2/*',
         'properties/rii/main/BaTiO3/*',
         'properties/rii/main/Be/*',
         'properties/rii/main/BeO/*',
         'properties/rii/main/Bi/*',
         'properties/rii/main/Bi12GeO20/*',
         'properties/rii/main/Bi12SiO20/*',
         'properties/rii/main/Bi4Ge3O12/*',
         'properties/rii/main/Bi4Ti3O12/*',
         'properties/rii/main/BiB3O6/*',
         'properties/rii/main/C/*',
         'properties/rii/main/CO2/*',
         'properties/rii/main/CS2/*',
         'properties/rii/main/Ca/*',
         'properties/rii/main/CaCO3/*',
         'properties/rii/main/CaF2/*',
         'properties/rii/main/CaMoO4/*',
         'properties/rii/main/CaWO4/*',
         'properties/rii/main/CdGeAs2/*',
         'properties/rii/main/CdGeP2/*',
         'properties/rii/main/CdS/*',
         'properties/rii/main/CdSe/*',
         'properties/rii/main/CdTe/*',
         'properties/rii/main/Ce/*',
         'properties/rii/main/Co/*',
         'properties/rii/main/Cr/*',
         'properties/rii/main/CsBr/*',
         'properties/rii/main/CsCl/*',
         'properties/rii/main/CsF/*',
         'properties/rii/main/CsI/*',
         'properties/rii/main/CsLiB6O10/*',
         'properties/rii/main/Cu/*',
         'properties/rii/main/CuCl/*',
         'properties/rii/main/CuGaS2/*',
         'properties/rii/main/D2/*',
         'properties/rii/main/D2O/*',
         'properties/rii/main/Dy2O3/*',
         'properties/rii/main/Er/*',
         'properties/rii/main/Eu/*',
         'properties/rii/main/Fe/*',
         'properties/rii/main/GaAs/*',
         'properties/rii/main/GaN/*',
         'properties/rii/main/GaP/*',
         'properties/rii/main/GaS/*',
         'properties/rii/main/GaSb/*',
         'properties/rii/main/GaSe/*',
         'properties/rii/main/Ge/*',
         'properties/rii/main/GeO2/*',
         'properties/rii/main/H2/*',
         'properties/rii/main/H2O/*',
         'properties/rii/main/He/*',
         'properties/rii/main/Hf/*',
         'properties/rii/main/Hg/*',
         'properties/rii/main/HgS/*',
         'properties/rii/main/Ho/*',
         'properties/rii/main/In/*',
         'properties/rii/main/InAs/*',
         'properties/rii/main/InP/*',
         'properties/rii/main/InSb/*',
         'properties/rii/main/Ir/*',
         'properties/rii/main/KBr/*',
         'properties/rii/main/KCl/*',
         'properties/rii/main/KF/*',
         'properties/rii/main/KH2PO4/*',
         'properties/rii/main/KI/*',
         'properties/rii/main/KNbO3/*',
         'properties/rii/main/KTaO3/*',
         'properties/rii/main/KTiOPO4/*',
         'properties/rii/main/Kr/*',
         'properties/rii/main/LaF3/*',
         'properties/rii/main/Li/*',
         'properties/rii/main/LiB3O5/*',
         'properties/rii/main/LiBr/*',
         'properties/rii/main/LiCaAlF6/*',
         'properties/rii/main/LiCl/*',
         'properties/rii/main/LiF/*',
         'properties/rii/main/LiI/*',
         'properties/rii/main/LiIO3/*',
         'properties/rii/main/LiNbO3/*',
         'properties/rii/main/Lu/*',
         'properties/rii/main/Lu2O3/*',
         'properties/rii/main/LuAl3(BO3)4/*',
         'properties/rii/main/Mg/*',
         'properties/rii/main/MgAl2O4/*',
         'properties/rii/main/MgF2/*',
         'properties/rii/main/MgO/*',
         'properties/rii/main/Mn/*',
         'properties/rii/main/Mo/*',
         'properties/rii/main/MoO3/*',
         'properties/rii/main/N2/*',
         'properties/rii/main/NH3/*',
         'properties/rii/main/NH4H2PO4/*',
         'properties/rii/main/Na/*',
         'properties/rii/main/NaBr/*',
         'properties/rii/main/NaCl/*',
         'properties/rii/main/NaF/*',
         'properties/rii/main/NaI/*',
         'properties/rii/main/Nb/*',
         'properties/rii/main/Nb2O5/*',
         'properties/rii/main/Ne/*',
         'properties/rii/main/Ni/*',
         'properties/rii/main/O2/*',
         'properties/rii/main/Os/*',
         'properties/rii/main/Pb/*',
         'properties/rii/main/Pb5Ge3O11/*',
         'properties/rii/main/PbF2/*',
         'properties/rii/main/PbMoO4/*',
         'properties/rii/main/PbS/*',
         'properties/rii/main/PbSe/*',
         'properties/rii/main/PbTe/*',
         'properties/rii/main/PbTiO3/*',
         'properties/rii/main/Pd/*',
         'properties/rii/main/Pr/*',
         'properties/rii/main/Pt/*',
         'properties/rii/main/RbBr/*',
         'properties/rii/main/RbCl/*',
         'properties/rii/main/RbF/*',
         'properties/rii/main/RbI/*',
         'properties/rii/main/RbTiOPO4/*',
         'properties/rii/main/Re/*',
         'properties/rii/main/Rh/*',
         'properties/rii/main/Ru/*',
         'properties/rii/main/Sc/*',
         'properties/rii/main/Sc2O3/*',
         'properties/rii/main/Se/*',
         'properties/rii/main/Si/*',
         'properties/rii/main/Si3N4/*',
         'properties/rii/main/SiC/*',
         'properties/rii/main/SiO/*',
         'properties/rii/main/SiO2/*',
         'properties/rii/main/Sn/*',
         'properties/rii/main/Sr/*',
         'properties/rii/main/SrF2/*',
         'properties/rii/main/SrMoO4/*',
         'properties/rii/main/SrTiO3/*',
         'properties/rii/main/Ta/*',
         'properties/rii/main/Ta2O5/*',
         'properties/rii/main/Te/*',
         'properties/rii/main/TeO2/*',
         'properties/rii/main/ThF4/*',
         'properties/rii/main/Ti/*',
         'properties/rii/main/TiO2/*',
         'properties/rii/main/Tl3AsSe3/*',
         'properties/rii/main/TlBr/*',
         'properties/rii/main/TlCl/*',
         'properties/rii/main/Tm/*',
         'properties/rii/main/V/*',
         'properties/rii/main/W/*',
         'properties/rii/main/Xe/*',
         'properties/rii/main/Y2O3/*',
         'properties/rii/main/Y3Al5O12/*',
         'properties/rii/main/YLiF4/*',
         'properties/rii/main/YVO4/*',
         'properties/rii/main/Yb/*',
         'properties/rii/main/Yb2O3/*',
         'properties/rii/main/Zn/*',
         'properties/rii/main/ZnGeP2/*',
         'properties/rii/main/ZnO/*',
         'properties/rii/main/ZnS/*',
         'properties/rii/main/ZnSe/*',
         'properties/rii/main/ZnSiAs2/*',
         'properties/rii/main/ZnTe/*',
         'properties/rii/main/Zr/*',
         'properties/rii/organic/(C16H14O3)n - polycarbonate/*',
         'properties/rii/organic/(C5O2H8)n - poly(methyl methacrylate)/*',
         'properties/rii/organic/(C6H10O5)n - cellulose/*',
         'properties/rii/organic/(C6H9NO)n - polyvinylpyrrolidone/*',
         'properties/rii/organic/(C8H8)n - polystyren/*',
         'properties/rii/organic/C2H3N - acetonitrile/*',
         'properties/rii/organic/C2H4O2 - acetic acid/*',
         'properties/rii/organic/C2H6O - ethanol/*',
         'properties/rii/organic/C2H6O2 - ethylene glycol/*',
         'properties/rii/organic/C3H6O - acetone/*',
         'properties/rii/organic/C3H8O - propanol/*',
         'properties/rii/organic/C3H8O2 - propylene glycol/*',
         'properties/rii/organic/C3H8O3 - glycerol/*',
         'properties/rii/organic/C4H10O - butanol/*',
         'properties/rii/organic/C4H8O2 - dioxane/*',
         'properties/rii/organic/C5H12 - pentane/*',
         'properties/rii/organic/C5H12O - pentanol/*',
         'properties/rii/organic/C5H12O2 - pentanediol/*',
         'properties/rii/organic/C6H12 - cyclohexane/*',
         'properties/rii/organic/C6H5NO2 - nitrobenzene/*',
         'properties/rii/organic/C6H6 - benzene/*',
         'properties/rii/organic/C7H8 - toluene/*',
         'properties/rii/organic/C8H18 - octane/*',
         'properties/rii/organic/C8H5KO4 - potassium hydrogen phthalate/*',
         'properties/rii/organic/C8H8 - styrene/*',
         'properties/rii/organic/C8H8O3 - methyl salicylate/*',
         'properties/rii/organic/C9H10O3 - ethyl salicylate/*',
         'properties/rii/organic/C9H8O - cinnamaldehyde/*',
         'properties/rii/organic/CCl4 - carbon tetrachloride/*',
         'properties/rii/organic/CH4 - methane/*',
         'properties/rii/organic/CH4N2O - urea/*',
         'properties/rii/organic/CH4O - methanol/*',
         'properties/rii/organic/CHBr3 - bromoform/*',
         'properties/rii/organic/CHCl3 - chloroform/*',
         'properties/rii/other/alloys/Nb-Sn/*',
         'properties/rii/other/alloys/V-Ga/*',
         'properties/rii/other/commercial plastics/CR-39/*',
         'properties/rii/other/commercial plastics/NAS-21/*',
         'properties/rii/other/commercial plastics/Optorez1330/*',
         'properties/rii/other/commercial plastics/ZeonexE48R/*',
         'properties/rii/other/doped crystals/Mg-LiTaO3/*',
         'properties/rii/other/doped crystals/Nb-RbTiOPO4/*',
         'properties/rii/other/exotic/metamaterials/*',
         'properties/rii/other/heat transfer fluids/Therminol VP-1/*',
         'properties/rii/other/index-matching liquids/cargille/*',
         'properties/rii/other/liquid crystals/5CB/*',
         'properties/rii/other/liquid crystals/5PCH/*',
         'properties/rii/other/liquid crystals/E44/*',
         'properties/rii/other/liquid crystals/E7/*',
         'properties/rii/other/liquid crystals/MLC-6241-000/*',
         'properties/rii/other/liquid crystals/MLC-6608/*',
         'properties/rii/other/liquid crystals/MLC-9200-000/*',
         'properties/rii/other/liquid crystals/MLC-9200-100/*',
         'properties/rii/other/liquid crystals/TL-216/*',
         'properties/rii/other/mixed crystals/AlGaAs/*',
         'properties/rii/other/mixed crystals/AlGaSb/*',
         'properties/rii/other/mixed crystals/AlON/*',
         'properties/rii/other/mixed crystals/GaInP/*',
         'properties/rii/other/mixed crystals/HfO2-Y2O3/*',
         'properties/rii/other/mixed crystals/In2O3-SnO2/*',
         'properties/rii/other/mixed crystals/TlBr-TlCl/*',
         'properties/rii/other/mixed crystals/TlBr-TlI/*',
         'properties/rii/other/mixed crystals/ZrO2-Y2O3/*',
         'properties/rii/other/mixed gases/air/*',
         'properties/rii/other/mixed organic/(C8H8)n-(C3H3N)m/*',
         'properties/rii/other/other/soot/*',
         'properties/rii/other/perovskite/CH3NH3PbI3/*',
         'properties/rii/other/resists/*']}

install_requires = \
['cairocffi>=1.1.0,<2.0.0',
 'chardet>=3.0.4,<4.0.0',
 'gizeh>=0.1.11,<0.2.0',
 'ipython>=7.14.0,<8.0.0',
 'mathx>=0.2,<0.3',
 'matplotlib>=3.2.1,<4.0.0',
 'numba>=0.49.1,<0.50.0',
 'numpy>=1.18.4,<2.0.0',
 'opt_einsum>=3.2.1,<4.0.0',
 'pyfftw>=0.12.0,<0.13.0',
 'pyopengl>=3.1.5,<4.0.0',
 'pyqt5>=5.12,<6.0',
 'pyqtgraph_extensions>=0.4.0,<0.5.0',
 'pyyaml>=5.3.1,<6.0.0']

entry_points = \
{'console_scripts': ['view-zmx = otk.rt2.cli:view_zmx']}

setup_kwargs = {
    'name': 'otk',
    'version': '0.1.2',
    'description': 'Optics Tool Kit',
    'long_description': '# otk - optics toolkit\n\nToolkit for doing optics in Python\n\n<img src="screenshots/zemax_conic_telecentric_lens.png" width="400  " title="conic telecentric lens with rays"><img src="screenshots/cell-phone-lens.png" width="160" title="cell phone lens"><img src="screenshots/csg.png" width="160" title="cell phone lens">\n\nFeatures include\n\n* 3D engine based on [sphere tracing](https://link.springer.com/article/10.1007/s003710050084) for simple robust implicit surfaces and constructive solid geometry,\n* nonsequential ray tracing engine,\n* programmatic lookup of full [RefractiveIndex.INFO](https://refractiveindex.info/) database,\n* import of lenses and glass catalogs from Zemax.\n\n## Installation\n\nInstallation methods include:\n\n* Clone repository and interact with it using [Poetry](https://python-poetry.org/) e.g. `poetry run view-zmx <zemax-file>` or `poetry shell`.\n* Install from package repository (e.g. PyPi) with pip: `pip install otk`.\n* Development mode with [: `poetry add <path-to-local-repo>`.\n* From package repository (e.g. PyPi) with Poetry: `poetry add otk`.\n\n## Getting started\n\n1. Check out the scripts in [examples](./examples).\n2. View one of the lenses in [designs](./designs) with the command line tool `view-zmx`.\n\n## Documentation\n\n(Yep, this is it at the moment.)\n\n### Command line tools\n\n`view-zmx <zemaxfile>` launches a viewer of a Zemax lens.\n\n### Packages\n\n* `otk.sdb` - Geometry library based on signed distance bounds.\n* `otk.rt1` - First attempt at ray tracing package. Superseded by otk.rt2.\n* `otk.rt2` - Ray tracing package with flexible geometry based on otk.sdb. See also `otk.rt2_scalar_qt`.\n* `otk.asbp` - Angular spectrum beam propagation.\n* `otk.abcd` - 1D ray transfer matrix ("ABCD matrices") tools.\n* `otk.rtm4` - abstractions for 1D ray transfer matrices, building upon `otk.abcd`.\n* `otk.pgb` - parabasal Gaussian routines for doing wave optical calculations with ray tracing results. Builds upon `otk.rt1`.\n* `otk.h4t` - homogeneous 4x4 transformation matrices.\n* `otk.paraxial` - basic paraxial optics calculations.\n* `otk.math` - various optics-specific math functions.\n* `otk.pov` - tools for generating POV-Ray scenes of optical setups.\n* `otk.pov` - for calculating properties of prisms.\n* `otk.qt` - Qt-related utilities\n* `otk.ri` - refractive index tools.\n* `otk.trains` - axially symmetric optical systems\n* `otk.v3` - operations on homogeneous vectors in 2D\n* `otk.v4` - operations on homogeneous vectors in 3D\n* `otk.v4b` - broadcasting operations on homogeneous vectors in 3D\n* `otk.zemax` - reading Zemax files\n\n## Roadmap\n\n* Import of wavelengths, field, and stop from Zemax.\n* Variables to allow rapid changes for animation and optimization.\n* Cool demos: rainbow, lighthouse.\n* Improve physical & wave optics.\n  * Upgrade parabasal Gaussians to use rt2.\n  * Upgrade asbp to use rt2.\n  * Demos e.g. spherical aberration acting on Gaussian beam, Arago spot.\n\n## Folder contents\n\n* `otk` - the Python package itself. Package data includes\n  * `otk/properties` - material properties databases.\n  * `otk/notes` - miscellaneous notes including derivations.\n* `examples` - example scripts.\n\n## Package management\n\notk uses [Poetry](https://python-poetry.org/) for package management. This means that dependencies, version, entry points etc are all defined in [`pyproject.toml`](./pyproject.toml).\n\n### Using [PyPi test instance](https://test.pypi.org/)\n\nTo setup, add test.pypi.org to your Poetry configuration with `poetry config repositories.test https://test.pypi.org/legacy/`. Note the [trailing slash](https://github.com/python-poetry/poetry/issues/742).\n\nTo publish (after `poetry build`), `poetry publish -r test`.\n\nTo test that it installs properly,\n1. create and activate a virtual environment, and\n2. per [instructions](https://packaging.python.org/guides/using-testpypi/), `pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple otk`.\n\nHowever, I was unable to re-upload the same version (i.e. to correct a mistake) to test.pypi.org (even after logging in to the website and deleting the release).\n\n## Testing\n\nTest framework is [pytest](https://docs.pytest.org/en/latest/) and [tox](https://tox.readthedocs.io/en/latest/).\n\n## Contributing\n\nPlease do.\n',
    'author': 'Dane Austin',
    'author_email': 'dane_austin@fastmail.com.au',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/draustin/otk',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)
