
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "dc31d9e9ed8b745d8c52e7f831057a76f83dba40",
 "version": "0.17.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
