
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-30T18:52:14-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a54b10442143e1fa1bc8b780769cefb1f5aebc0",
 "version": "0.3.3rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
