from setuptools import setup
from setuptools import find_packages





setup(
    name="netoprmgr",
    version="v1.3.3",
    description="Project to Manage Network Operation.",
    long_description="Project to Manage Network Operation.\nType 'python -m netoprmgr.__main__' to run program.\nNow using flask",
    #long_description_content_type="text/markdown",
    url="https://github.com/FunGuardian/netoprmgr",
    author="Funguardian, Dedar, Luthfi",
    author_email="cristiano.ramadhan@gmail.com",
    license="GPLv3+",
    packages=find_packages(exclude=("test*",)),
    install_requires=[
	'appdirs==1.4.3',
	'bcrypt==3.1.7',
	'CacheControl==0.12.6',
	'certifi==2019.11.28',
	'cffi==1.14.0',
	'chardet==3.0.4',
	'click==7.1.2',
	'colorama==0.4.3',
	'contextlib2==0.6.0',
	'cryptography==2.9.2',
	'distlib==0.3.0',
	'distro==1.4.0',
	'Flask==1.1.2',
	'Flask-Bcrypt==0.7.1',
	'Flask-Login==0.5.0',
	'Flask-SQLAlchemy==2.4.1',
	'Flask-WTF==0.14.3',
	'future==0.18.2',
	'html5lib==1.0.1',
	'idna==2.8',
	'ipaddr==2.2.0',
	'itsdangerous==1.1.0',
	'Jinja2==2.11.2',
	'lockfile==0.12.2',
	'lxml==4.5.0',
	'MarkupSafe==1.1.1',
	'msgpack==0.6.2',
	'netmiko==3.1.0',
	'packaging==20.3',
	'paramiko==2.7.1',
	'pep517==0.8.2',
	'progress==1.5',
	'pycparser==2.20',
	'PyNaCl==1.3.0',
	'pyparsing==2.4.6',
	'pyserial==3.4',
	'python-docx==0.8.10',
	'pytoml==0.1.21',
	'requests==2.22.0',
	'retrying==1.3.3',
	'scp==0.13.2',
	'six==1.14.0',
	'SQLAlchemy==1.3.16',
	'textfsm==1.1.0',
	'urllib3==1.25.8',
	'webencodings==0.5.1',
	'Werkzeug==1.0.1',
	'WTForms==2.3.1',
	'xlrd==1.2.0',
	'XlsxWriter==1.2.8',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
        'Programming Language :: Python :: 3.6'
    ],
    include_package_data=True
)
