# Generated by Django 3.0.5 on 2020-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='audiences',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
