
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-25T19:31:16+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d21458303fd47d5368b559f98bba05348ae37ea",
 "version": "1.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
