# Generated by Django 2.0.13 on 2020-04-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200421_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_timed',
            new_name='created_time',
        ),
    ]
