
VOID_ARG_PREAMBLE = 'V'
INT_ARG_PREAMBLE = 'I'
INT_INT_ARG_PREAMBLE = 'H'
STRING_ARG_PREAMBLE = 'S'
FLOAT_ARG_PREAMBLE = 'F'

CMD_PREAMBLE = "MArC_cmd"
RESULT_PREAMBLE = "MArC_res"
ERROR_PREAMBLE = "MArC_err"
MESSAGE_PREAMBLE = "MArC_msg"

