MUNICIPALITIES = (
    "Abrantes",
    "Albergaria-a-Velha",
    "Albufeira",
    "Alcanena",
    "Alcobaça",
    "Alcochete",
    "Alcácer do Sal",
    "Alenquer",
    "Alfândega da Fé",
    "Alijó",
    "Almada",
    "Almeida",
    "Almeirim",
    "Almodôvar",
    "Alpiarça",
    "Alvaiázere",
    "Amadora",
    "Amarante",
    "Amares",
    "Anadia",
    "Ansião",
    "António",
    "Arcos de Valdevez",
    "Arganil",
    "Arouca",
    "Arruda dos Vinhos",
    "Aveiro",
    "Azambuja",
    "Baião",
    "Barcelos",
    "Barreiro",
    "Batalha",
    "Beja",
    "Benavente",
    "Bombarral",
    "Braga",
    "Bragança",
    "Cabeceiras de Basto",
    "Cadaval",
    "Caldas da Rainha",
    "Calheta",
    "Caminha",
    "Cantanhede",
    "Carrazeda de Ansiães",
    "Carregal do Sal",
    "Cartaxo",
    "Cascais",
    "Castelo Branco",
    "Castelo de Paiva",
    "Castro Daire",
    "Castro Marim",
    "Celorico da Beira",
    "Celorico de Basto",
    "Chamusca",
    "Chaves",
    "Cinfães",
    "Coimbra",
    "Condeixa-a-Nova",
    "Coruche",
    "Covilhã",
    "Cuba",
    "Câmara de Lobos",
    "Elvas",
    "Entroncamento",
    "Espinho",
    "Esposende",
    "Estarreja",
    "Fafe",
    "Faro",
    "Felgueiras",
    "Figueira de Castelo Rodrigo",
    "Figueira da Foz",
    "Figueiró dos Vinhos",
    "Fornos de Algodres",
    "Funchal",
    "Fundão",
    "Gondomar",
    "Gouveia",
    "Grândola",
    "Guarda",
    "Guimarães",
    "Góis",
    "Horta",
    "Lagoa",
    "Lagos",
    "Lamego",
    "Leiria",
    "Lisboa",
    "Loulé",
    "Loures",
    "Lourinhã",
    "Lousada",
    "Lousã",
    "Macedo de Cavaleiros",
    "Madalena",
    "Mafra",
    "Maia",
    "Mangualde",
    "Manteigas",
    "Marco de Canaveses",
    "Marinha Grande",
    "Matosinhos",
    "Mealhada",
    "Melgaço",
    "Mira",
    "Miranda do Corvo",
    "Miranda do Douro",
    "Mirandela",
    "Mogadouro",
    "Moimenta da Beira",
    "Moita",
    "Monchique",
    "Monsaraz",
    "Montalegre",
    "Montemor-o-Novo",
    "Montemor-o-Velho",
    "Montijo",
    "Monção",
    "Mortágua",
    "Moura",
    "Murtosa",
    "Murça",
    "Nelas",
    "Nordeste",
    "Odemira",
    "Odivelas",
    "Oeiras",
    "Olhão",
    "Oliveira de Azeméis",
    "Oliveira de Frades",
    "Oliveira do Bairro",
    "Oliveira do Hospital",
    "Ourém",
    "Ovar",
    "Palmela",
    "Paredes",
    "Paredes de Coura",
    "Paços de Ferreira",
    "Pedrógão Grande",
    "Penacova",
    "Penafiel",
    "Penaguião",
    "Penela",
    "Peniche",
    "Peso da Régua",
    "Pinhel",
    "Pombal",
    "Ponta Delgada",
    "Ponta do Sol",
    "Ponte da Barca",
    "Ponte de Lima",
    "Ponte de Sor",
    "Portalegre",
    "Portel",
    "Portimão",
    "Porto",
    "Porto Santo",
    "Porto de Mós",
    "Póvoa de Lanhoso",
    "Póvoa de Varzim",
    "Reguengos de Monsaraz",
    "Resende",
    "Ribeira de Pena",
    "Rio Maior",
    "Sabrosa",
    "Salvaterra de Magos",
    "Santa Comba Dão",
    "Santa Cruz",
    "Santa Maria da Feira",
    "Santa Marta de Penaguião",
    "Santarém",
    "Santiago do Cacém",
    "Santo Tirso",
    "Seia",
    "Seixal",
    "Sernancelhe",
    "Serpa",
    "Sertã",
    "Sesimbra",
    "Setúbal",
    "Sever do Vouga",
    "Silves",
    "Sines",
    "Sintra",
    "Sobral de Monte Agraço",
    "Soure",
    "Sátão",
    "São Brás de Alportel",
    "São João da Madeira",
    "São Pedro do Sul",
    "São Roque do Pico",
    "Tavira",
    "Terras de Bouro",
    "Tomar",
    "Tondela",
    "Torre de Moncorvo",
    "Torres Novas",
    "Torres Vedras",
    "Trancoso",
    "Trofa",
    "Tábua",
    "Vagos",
    "Vale de Cambra",
    "Valença",
    "Valongo",
    "Valpaços",
    "Velas",
    "Vendas Novas",
    "Viana do Castelo",
    "Vieira do Minho",
    "Vila Flor",
    "Vila Franca de Xira",
    "Vila Nova da Barquinha",
    "Vila Nova de Cerveira",
    "Vila Nova de Famalicão",
    "Vila Nova de Foz Côa",
    "Vila Nova de Gaia",
    "Vila Nova de Poiares",
    "Vila Pouca de Aguiar",
    "Vila Real",
    "Vila Real de Santo António",
    "Vila Verde",
    "Vila da Praia da Vitória",
    "Vila do Conde",
    "Vimioso",
    "Vinhais",
    "Viseu",
    "Vizela",
    "Vouzela",
    "Águeda",
    "Évora",
    "Ílhavo",
    "Óbidos",
)
