# Generated by Django 3.0.6 on 2020-05-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corgy_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollmodel',
            options={'verbose_name': 'Payroll'},
        ),
    ]
