# Generated by Django 3.0.6 on 2020-05-23 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corgy_mdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentmodel',
            name='begin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='begin'),
        ),
        migrations.AlterField(
            model_name='employmentmodel',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='employmentmodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corgy_mdm.OrganizationModel', verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='employmentmodel',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corgy_mdm.PersonModel', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='organizationmodel',
            name='registration_number',
            field=models.CharField(max_length=500, verbose_name='registration_number'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='birthdate',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='birthplace',
            field=models.CharField(max_length=200, verbose_name='birth place'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], default=None, max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='name_of_mother',
            field=models.CharField(default=None, max_length=200, verbose_name='name of mother'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='name_prefix',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('senior', 'Senior'), ('doctor', 'Doctor'), ('professor', 'Professor'), ('widow', 'Widow')], default=None, max_length=10, null=True, verbose_name='name prefix'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='name_suffix',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='name suffix'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='tax_number',
            field=models.CharField(max_length=100, verbose_name='tax number'),
        ),
    ]
