# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/Public/prog/python3/prettyetc/prettyetc/qtui/components/design/mainwindow.ui',
# licensing of '/home/Public/prog/python3/prettyetc/prettyetc/qtui/components/design/mainwindow.ui' applies.
#
# Created: Fri Aug 16 18:22:27 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 380)
        MainWindow.setAutoFillBackground(False)
        self.root = QtWidgets.QWidget(MainWindow)
        self.root.setAutoFillBackground(False)
        self.root.setObjectName("root")
        self.rootLayout = QtWidgets.QGridLayout(self.root)
        self.rootLayout.setContentsMargins(0, 0, 0, 0)
        self.rootLayout.setObjectName("rootLayout")
        self.confTabs = QtWidgets.QTabWidget(self.root)
        self.confTabs.setStyleSheet("border: 2px solid transparent;\n"
"")
        self.confTabs.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.confTabs.setElideMode(QtCore.Qt.ElideRight)
        self.confTabs.setTabsClosable(True)
        self.confTabs.setMovable(True)
        self.confTabs.setObjectName("confTabs")
        self.rootLayout.addWidget(self.confTabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.root)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 30))
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_saveas = QtWidgets.QAction(MainWindow)
        self.action_saveas.setObjectName("action_saveas")
        self.action_preferences = QtWidgets.QAction(MainWindow)
        self.action_preferences.setObjectName("action_preferences")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menufile.addAction(self.action_new)
        self.menufile.addAction(self.action_open)
        self.menufile.addAction(self.action_save)
        self.menufile.addAction(self.action_saveas)
        self.menuSettings.addAction(self.action_preferences)
        self.menuInfo.addAction(self.action_about)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())
        self.toolBar.addAction(self.action_new)
        self.toolBar.addAction(self.action_open)
        self.toolBar.addAction(self.action_save)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_preferences)

        self.retranslateUi(MainWindow)
        self.confTabs.setCurrentIndex(-1)
        QtCore.QObject.connect(self.action_open, QtCore.SIGNAL("triggered()"), MainWindow.open_confile)
        QtCore.QObject.connect(self.action_preferences, QtCore.SIGNAL("triggered()"), MainWindow.open_settings)
        QtCore.QObject.connect(self.action_about, QtCore.SIGNAL("triggered()"), MainWindow.open_about)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.menufile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.menuInfo.setTitle(QtWidgets.QApplication.translate("MainWindow", "Info", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.action_new.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.action_new.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, -1))
        self.action_open.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.action_open.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+O", None, -1))
        self.action_save.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.action_save.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.action_saveas.setText(QtWidgets.QApplication.translate("MainWindow", "Save as", None, -1))
        self.action_saveas.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, -1))
        self.action_preferences.setText(QtWidgets.QApplication.translate("MainWindow", "Preferences", None, -1))
        self.action_about.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

