index = {"'cause": ['because'],
 '0': ['zero'],
 '1': ['one', 'won'],
 '10': ['ten'],
 '100': ['one hundred'],
 '11': ['eleven'],
 '12': ['twelve'],
 '13': ['thirteen'],
 '14': ['fourteen'],
 '15': ['fifteen'],
 '16': ['sixteen'],
 '17': ['seventeen'],
 '18': ['eighteen'],
 '19': ['nineteen'],
 '2': ['to', 'toe', 'too', 'tow', 'two'],
 '20': ['twenty'],
 '21': ['twenty-one'],
 '22': ['twenty-two'],
 '23': ['twenty-three'],
 '24': ['twenty-four'],
 '25': ['twenty-five'],
 '26': ['twenty-six'],
 '27': ['twenty-seven'],
 '28': ['twenty-eight'],
 '29': ['twenty-nine'],
 '3': ['three'],
 '30': ['thirty'],
 '31': ['thirty-one'],
 '32': ['thirty-two'],
 '33': ['thirty-three'],
 '34': ['thirty-four'],
 '35': ['thirty-five'],
 '36': ['thirty-six'],
 '37': ['thirty-seven'],
 '38': ['thirty-eight'],
 '39': ['thirty-nine'],
 '4': ['for', 'fore', 'forth', 'four', 'fourth'],
 '40': ['forty'],
 '41': ['forty-one'],
 '42': ['forty-two'],
 '43': ['forty-three'],
 '44': ['forty-four'],
 '45': ['forty-five'],
 '46': ['forty-six'],
 '47': ['forty-seven'],
 '48': ['forty-eight'],
 '49': ['forty-nine'],
 '5': ['five'],
 '50': ['fifty'],
 '51': ['fifty-one'],
 '52': ['fifty-two'],
 '53': ['fifty-three'],
 '54': ['fifty-four'],
 '55': ['fifty-five'],
 '56': ['fifty-six'],
 '57': ['fifty-seven'],
 '58': ['fifty-eight'],
 '59': ['fifty-nine'],
 '6': ['six'],
 '60': ['sixty'],
 '61': ['sixty-one'],
 '62': ['sixty-two'],
 '63': ['sixty-three'],
 '64': ['sixty-four'],
 '65': ['sixty-five'],
 '66': ['sixty-six'],
 '67': ['sixty-seven'],
 '68': ['sixty-eight'],
 '69': ['sixty-nine'],
 '7': ['seven'],
 '70': ['seventy'],
 '71': ['seventy-one'],
 '72': ['seventy-two'],
 '73': ['seventy-three'],
 '74': ['seventy-four'],
 '75': ['seventy-five'],
 '76': ['seventy-six'],
 '77': ['seventy-seven'],
 '78': ['seventy-eight'],
 '79': ['seventy-nine'],
 '8': ['ate', 'eight'],
 '80': ['eighty'],
 '81': ['eighty-one'],
 '82': ['eighty-two'],
 '83': ['eighty-three'],
 '84': ['eighty-four'],
 '85': ['eighty-five'],
 '86': ['eighty-six'],
 '87': ['eighty-seven'],
 '88': ['eighty-eight'],
 '89': ['eighty-nine'],
 '9': ['nine'],
 '90': ['ninety'],
 '91': ['ninety-one'],
 '92': ['ninety-two'],
 '93': ['ninety-three'],
 '94': ['ninety-four'],
 '95': ['ninety-five'],
 '96': ['ninety-six'],
 '97': ['ninety-seven'],
 '98': ['ninety-eight'],
 '99': ['ninety-nine'],
 'accede': ['exceed'],
 'accept': ['except'],
 'access': ['excess'],
 'accessary': ['accessory'],
 'accessory': ['accessary'],
 'ad': ['add', 'at'],
 'adapt': ['adept', 'adopt'],
 'add': ['ad', 'at'],
 'adept': ['adapt', 'adopt'],
 'adopt': ['adapt', 'adept'],
 'advice': ['advise'],
 'advise': ['advice'],
 'aerie': ['airy', 'eerie'],
 'aid': ['aide'],
 'aide': ['aid'],
 'ail': ['ale'],
 'air': ['ere', 'heir'],
 'airy': ['aerie', 'eerie'],
 'aisle': ['i shall', 'i will', "i'll", 'isle'],
 'ale': ['ail'],
 'all': ['awl'],
 'alley': ['ally'],
 'allowed': ['aloud'],
 'allready': ['already'],
 'allude': ['elude'],
 'allusion': ['illusion'],
 'ally': ['alley'],
 'alms': ['arms'],
 'aloud': ['allowed'],
 'already': ['allready'],
 'altar': ['alter'],
 'alter': ['altar'],
 'an': ['and', 'end', 'in', 'inn'],
 'and': ['an', 'end', 'in', 'inn'],
 'ant': ['are not', "aren't", 'aunt'],
 'appear': ['peer', 'pier', 'pure'],
 'appraise': ['apprise'],
 'apprise': ['appraise'],
 'arc': ['ark'],
 'are': ['r'],
 'are not': ['ant', "aren't", 'aunt'],
 "aren't": ['ant', 'are not', 'aunt'],
 'ark': ['arc'],
 'arms': ['alms'],
 'ascent': ['assent'],
 'assay': ['essay'],
 'assent': ['ascent'],
 'at': ['ad', 'add'],
 'ate': ['8', 'eight'],
 'attendance': ['attendants'],
 'attendants': ['attendance'],
 'auger': ['augur'],
 'aught': ['ought'],
 'augur': ['auger'],
 'auk': ['orc'],
 'aunt': ['ant', 'are not', "aren't"],
 'aural': ['oral'],
 'auricle': ['oracle'],
 'average': ['median', 'normal'],
 'away': ['aweigh'],
 'awe': ['oar', 'oh', 'or', 'ore', 'owe'],
 'aweigh': ['away'],
 'awl': ['all'],
 'axel': ['axle'],
 'axes': ['axis'],
 'axis': ['axes'],
 'axle': ['axel'],
 'aye': ['eye', 'i'],
 'bail': ['bale'],
 'bait': ['bate'],
 'baited': ['bated'],
 'baize': ['bays'],
 'bald': ['bawled'],
 'bale': ['bail'],
 'ball': ['bawl'],
 'band': ['banned'],
 'banned': ['band'],
 'bard': ['barred'],
 'bare': ['bear'],
 'bark': ['barque'],
 'baron': ['barren'],
 'barque': ['bark'],
 'barred': ['bard'],
 'barren': ['baron'],
 'base': ['bass'],
 'based': ['baste'],
 'bases': ['basis'],
 'basis': ['bases'],
 'bass': ['base'],
 'baste': ['based'],
 'bate': ['bait'],
 'bated': ['baited'],
 'bawl': ['ball'],
 'bawled': ['bald'],
 'bay': ['bey'],
 'bays': ['baize'],
 'bazaar': ['bizarre'],
 'be': ['bee'],
 'beach': ['beech'],
 'bean': ['been'],
 'bear': ['bare'],
 'beat': ['beet'],
 'beau': ['bough', 'bow'],
 'because': ["'cause"],
 'bee': ['be'],
 'beech': ['beach'],
 'been': ['bean'],
 'beer': ['bier'],
 'beet': ['beat'],
 'bel': ['bell', 'belle'],
 'bell': ['bel', 'belle'],
 'belle': ['bel', 'bell'],
 'berry': ['bury'],
 'berth': ['birth'],
 'bey': ['bay'],
 'bier': ['beer'],
 'bight': ['bite', 'byte'],
 'billed': ['build'],
 'birth': ['berth'],
 'bite': ['bight', 'byte'],
 'bitten': ['bittern'],
 'bittern': ['bitten'],
 'bizarre': ['bazaar'],
 'blew': ['blue'],
 'bloc': ['block'],
 'block': ['bloc'],
 'blue': ['blew'],
 'boar': ['bore'],
 'board': ['bored'],
 'boarder': ['border'],
 'bold': ['bowled'],
 'bolder': ['boulder'],
 'boos': ['booze'],
 'bootie': ['booty'],
 'booty': ['bootie'],
 'booze': ['boos'],
 'border': ['boarder'],
 'bore': ['boar'],
 'bored': ['board'],
 'born': ['borne'],
 'borne': ['born'],
 'borough': ['burro', 'burrow'],
 'bough': ['beau', 'bow'],
 'bouillon': ['bullion'],
 'boulder': ['bolder'],
 'bow': ['beau', 'bough'],
 'bowled': ['bold'],
 'boy': ['buoy'],
 'brae': ['bray'],
 'braid': ['brayed'],
 'braise': ['brays', 'braze'],
 'brake': ['break'],
 'bray': ['brae'],
 'brayed': ['braid'],
 'brays': ['braise', 'braze'],
 'braze': ['braise', 'brays'],
 'breach': ['breech'],
 'bread': ['bred'],
 'break': ['brake'],
 'bred': ['bread'],
 'breech': ['breach'],
 'brewed': ['brood'],
 'brews': ['bruise'],
 'bridal': ['bridle'],
 'bridle': ['bridal'],
 'bring': ['take'],
 'broach': ['brooch'],
 'brooch': ['broach'],
 'brood': ['brewed'],
 'brows': ['browse'],
 'browse': ['brows'],
 'bruise': ['brews'],
 'build': ['billed'],
 'bullion': ['bouillon'],
 'buoy': ['boy'],
 'bur': ['burr'],
 'burr': ['bur'],
 'burro': ['borough', 'burrow'],
 'burrow': ['borough', 'burro'],
 'bury': ['berry'],
 'but': ['butt'],
 'butt': ['but'],
 'buy': ['by', 'bye'],
 'buyer': ['byre'],
 'by': ['buy', 'bye'],
 'bye': ['buy', 'by'],
 'byre': ['buyer'],
 'byte': ['bight', 'bite'],
 'caddie': ['caddy'],
 'caddy': ['caddie'],
 'calendar': ['calender'],
 'calender': ['calendar'],
 'call': ['caul'],
 'callous': ['callus'],
 'callus': ['callous'],
 "can't": ['cannot'],
 'cannon': ['canon'],
 'cannot': ["can't"],
 'canon': ['cannon'],
 'canter': ['cantor'],
 'cantor': ['canter'],
 'canvas': ['canvass'],
 'canvass': ['canvas'],
 'capital': ['capitol'],
 'capitol': ['capital'],
 'carat': ['carrot'],
 'carol': ['carrel'],
 'carrel': ['carol'],
 'carrot': ['carat'],
 'cast': ['caste'],
 'caste': ['cast'],
 'caster': ['castor'],
 'castor': ['caster'],
 'caught': ['court'],
 'caul': ['call'],
 'caw': ['core', 'corps'],
 'cede': ['seed'],
 'ceiling': ['sealing'],
 'cell': ['sell'],
 'cellar': ['seller'],
 'censer': ['censor', 'censure', 'sensor'],
 'censor': ['censer', 'censure', 'sensor'],
 'censure': ['censer', 'censor', 'sensor'],
 'census': ['sense'],
 'cent': ['scent', 'sent'],
 'cereal': ['serial'],
 'cession': ['session'],
 'chance': ['chants'],
 'chantey': ['shanty'],
 'chants': ['chance'],
 'chased': ['chaste'],
 'chaste': ['chased'],
 'cheap': ['cheep'],
 'check': ['cheque'],
 'cheep': ['cheap'],
 'cheque': ['check'],
 'chews': ['choose'],
 'chic': ['sheik'],
 'chile': ['chili', 'chilli', 'chilly'],
 'chili': ['chile', 'chilli', 'chilly'],
 'chilli': ['chile', 'chili', 'chilly'],
 'chilly': ['chile', 'chili', 'chilli'],
 'choir': ['quire'],
 'choose': ['chews'],
 'choral': ['coral'],
 'chord': ['cord', 'cored'],
 'chute': ['shoot'],
 'cite': ['sight', 'site'],
 'clack': ['claque'],
 'claque': ['clack'],
 'clause': ['claws'],
 'claws': ['clause'],
 'clew': ['clue'],
 'climb': ['clime'],
 'clime': ['climb'],
 'close': ['clothes', 'cloze'],
 'clothes': ['close', 'cloze'],
 'cloze': ['close', 'clothes'],
 'clue': ['clew'],
 'coal': ['kohl'],
 'coarse': ['course'],
 'coign': ['coin'],
 'coin': ['coign'],
 'colonel': ['kernel'],
 'complacent': ['complaisant'],
 'complaisant': ['complacent'],
 'complement': ['compliment'],
 'compliment': ['complement'],
 'confidant': ['confident'],
 'confident': ['confidant'],
 'coo': ['coup'],
 'cops': ['copse'],
 'copse': ['cops'],
 'coral': ['choral'],
 'cord': ['chord', 'cored'],
 'core': ['caw', 'corps'],
 'cored': ['chord', 'cord'],
 'corps': ['caw', 'core'],
 'could have': ["could've"],
 'could not': ["couldn't"],
 "could've": ['could have'],
 "couldn't": ['could not'],
 'council': ['counsel'],
 'counsel': ['council'],
 'coup': ['coo'],
 'course': ['coarse'],
 'court': ['caught'],
 'cousin': ['cozen'],
 'coward': ['cowered'],
 'cowered': ['coward'],
 'cozen': ['cousin'],
 'crate': ['create'],
 'creak': ['creek'],
 'create': ['crate'],
 'creek': ['creak'],
 'crewel': ['cruel'],
 'crews': ['cruise'],
 'cruel': ['crewel'],
 'cruise': ['crews'],
 'cue': ['kyu', 'queue'],
 'curb': ['kerb'],
 'currant': ['current'],
 'current': ['currant'],
 'cygnet': ['signet'],
 'cymbal': ['cymbol', 'symbol'],
 'cymbol': ['cymbal', 'symbol'],
 'dam': ['damn'],
 'damn': ['dam'],
 'days': ['daze'],
 'daze': ['days'],
 'dear': ['deer'],
 'deer': ['dear'],
 'dense': ['dents'],
 'dents': ['dense'],
 'depravation': ['deprivation'],
 'deprivation': ['depravation'],
 'descent': ['dissent'],
 'desert': ['dessert'],
 'desperate': ['disparate'],
 'dessert': ['desert'],
 'deviser': ['divisor'],
 'dew': ['do', 'due'],
 'did not': ["didn't"],
 "didn't": ['did not'],
 'die': ['dye'],
 'disburse': ['disperse'],
 'discreet': ['discrete'],
 'discrete': ['discreet'],
 'disparate': ['desperate'],
 'disperse': ['disburse'],
 'dissent': ['descent'],
 'divisor': ['deviser'],
 'do': ['dew', 'due'],
 'do not': ['does not', "doesn't", "don't"],
 'doe': ['doh', 'dough'],
 'does': ['doze'],
 'does not': ['do not', "doesn't", "don't"],
 "doesn't": ['do not', 'does not', "don't"],
 'doh': ['doe', 'dough'],
 "don't": ['do not', 'does not', "doesn't"],
 'done': ['dun'],
 'dough': ['doe', 'doh'],
 'douse': ['dowse'],
 'dowse': ['douse'],
 'doze': ['does'],
 'draft': ['draught'],
 'draught': ['draft'],
 'drying': ['trying'],
 'dual': ['duel'],
 'due': ['dew', 'do'],
 'duel': ['dual'],
 'dun': ['done'],
 'dye': ['die'],
 'dyeing': ['dying'],
 'dying': ['dyeing'],
 'each': ['either'],
 'earn': ['urn'],
 'eave': ['eve'],
 'ecology': ['environment'],
 'eek': ['eke'],
 'eerie': ['aerie', 'airy'],
 'eery': ['eyrie'],
 'eight': ['8', 'ate'],
 'eighteen': ['18'],
 'eighty': ['80'],
 'eighty-eight': ['88'],
 'eighty-five': ['85'],
 'eighty-four': ['84'],
 'eighty-nine': ['89'],
 'eighty-one': ['81'],
 'eighty-seven': ['87'],
 'eighty-six': ['86'],
 'eighty-three': ['83'],
 'eighty-two': ['82'],
 'either': ['each'],
 'eke': ['eek'],
 'eleven': ['11'],
 'elicit': ['illicit'],
 'elude': ['allude'],
 'eminent': ['imminent'],
 'end': ['an', 'and', 'in', 'inn'],
 'environment': ['ecology'],
 'epic': ['epoch'],
 'epoch': ['epic'],
 'ere': ['air', 'heir'],
 'essay': ['assay'],
 'eve': ['eave'],
 'everybody is': ["everybody's"],
 "everybody's": ['everybody is'],
 'everyone is': ["everyone's"],
 "everyone's": ['everyone is'],
 'ewe': ['yew', 'you'],
 'ewes': ['use', 'yews'],
 'exceed': ['accede'],
 'except': ['accept'],
 'excess': ['access'],
 'extant': ['extent'],
 'extent': ['extant'],
 'eye': ['aye', 'i'],
 'eyelet': ['islet'],
 'eyrie': ['eery'],
 'facts': ['fax'],
 'fah': ['far'],
 'fail': ['feel'],
 'fain': ['feign'],
 'faint': ['feint'],
 'fair': ['fare'],
 'fairy': ['ferry'],
 'far': ['fah'],
 'fare': ['fair'],
 'farther': ['father'],
 'fat': ['vat'],
 'father': ['farther'],
 'faun': ['fawn'],
 'fawn': ['faun'],
 'fax': ['facts'],
 'fay': ['fey'],
 'faze': ['phase'],
 'feat': ['feet', 'fete'],
 'feel': ['fail'],
 'feet': ['feat', 'fete'],
 'feign': ['fain'],
 'feint': ['faint'],
 'ferrule': ['ferule'],
 'ferry': ['fairy'],
 'ferule': ['ferrule'],
 'fete': ['feat', 'feet'],
 'few': ['phew'],
 'fey': ['fay'],
 'fie': ['phi'],
 'fifteen': ['15'],
 'fifty': ['50'],
 'fifty-eight': ['58'],
 'fifty-five': ['55'],
 'fifty-four': ['54'],
 'fifty-nine': ['59'],
 'fifty-one': ['51'],
 'fifty-seven': ['57'],
 'fifty-six': ['56'],
 'fifty-three': ['53'],
 'fifty-two': ['52'],
 'file': ['phial'],
 'find': ['fined'],
 'fined': ['find'],
 'fir': ['fur'],
 'fisher': ['fissure'],
 'fissure': ['fisher'],
 'five': ['5'],
 'fizz': ['phiz'],
 'flair': ['flare'],
 'flare': ['flair'],
 'flaw': ['floor'],
 'flea': ['flee'],
 'flecks': ['flex'],
 'flee': ['flea'],
 'flew': ['flu', 'flue'],
 'flex': ['flecks'],
 'floe': ['flow'],
 'floor': ['flaw'],
 'flour': ['flower'],
 'flow': ['floe'],
 'flower': ['flour'],
 'flu': ['flew', 'flue'],
 'flue': ['flew', 'flu'],
 'foaled': ['fold'],
 'fold': ['foaled'],
 'for': ['4', 'fore', 'forth', 'four', 'fourth'],
 'forbear': ['forebear'],
 'fore': ['4', 'for', 'forth', 'four', 'fourth'],
 'forebear': ['forbear'],
 'foreword': ['forward'],
 'formally': ['formerly'],
 'formerly': ['formally'],
 'fort': ['fought'],
 'forth': ['4', 'for', 'fore', 'four', 'fourth'],
 'forty': ['40'],
 'forty-eight': ['48'],
 'forty-five': ['45'],
 'forty-four': ['44'],
 'forty-nine': ['49'],
 'forty-one': ['41'],
 'forty-seven': ['47'],
 'forty-six': ['46'],
 'forty-three': ['43'],
 'forty-two': ['42'],
 'forward': ['foreword'],
 'fought': ['fort'],
 'foul': ['fowl'],
 'four': ['4', 'for', 'fore', 'forth', 'fourth'],
 'fourteen': ['14'],
 'fourth': ['4', 'for', 'fore', 'forth', 'four'],
 'fowl': ['foul'],
 'franc': ['frank'],
 'frank': ['franc'],
 'frays': ['phrase'],
 'freeze': ['frieze'],
 'friar': ['fryer'],
 'frieze': ['freeze'],
 'fryer': ['friar'],
 'fur': ['fir'],
 'furs': ['furze'],
 'furze': ['furs'],
 'gaff': ['gaffe'],
 'gaffe': ['gaff'],
 'gage': ['gauge'],
 'gait': ['gate'],
 'galipot': ['gallipot'],
 'gallipot': ['galipot'],
 'gallop': ['galop'],
 'galop': ['gallop'],
 'gamble': ['gambol'],
 'gambol': ['gamble'],
 'gate': ['gait'],
 'gauge': ['gage'],
 'gays': ['gaze'],
 'gaze': ['gays'],
 'gel': ['jell'],
 'gene': ['jean'],
 'genes': ['jeans'],
 'genius': ['genus'],
 'genus': ['genius'],
 'gibe': ['jibe'],
 'gild': ['guild'],
 'gilt': ['guilt'],
 'gimme': ['give me'],
 'giro': ['gyro'],
 'gist': ['jest'],
 'give me': ['gimme'],
 'glacier': ['glazier'],
 'glazier': ['glacier'],
 'gnaw': ['naw', 'nor'],
 'gneiss': ['nice'],
 'gnu': ['knew', 'new'],
 'gofer': ['gopher'],
 'going to': ['gonna'],
 'gonna': ['going to'],
 'gopher': ['gofer'],
 'gored': ['gourd'],
 'gorilla': ['guerilla', 'guerrilla'],
 'gourd': ['gored'],
 'grade': ['grate', 'great', 'grid'],
 'grate': ['grade', 'great', 'grid'],
 'graze': ['greys'],
 'grease': ['greece'],
 'great': ['grade', 'grate', 'grid'],
 'greave': ['grieve'],
 'greece': ['grease'],
 'greys': ['graze'],
 'grid': ['grade', 'grate', 'great'],
 'grieve': ['greave'],
 'grill': ['grille'],
 'grille': ['grill'],
 'grisly': ['grizzly'],
 'grizzly': ['grisly'],
 'groan': ['grown'],
 'grown': ['groan'],
 'guarantee': ['guaranty'],
 'guaranty': ['guarantee'],
 'guerilla': ['gorilla', 'guerrilla'],
 'guerrilla': ['gorilla', 'guerilla'],
 'guessed': ['guest'],
 'guest': ['guessed'],
 'guild': ['gild'],
 'guilt': ['gilt'],
 'guise': ['guys'],
 'guys': ['guise'],
 'gyro': ['giro'],
 'had not': ["hadn't"],
 "hadn't": ['had not'],
 'hail': ['hale'],
 'hair': ['hare'],
 'hairier': ['harrier'],
 'hale': ['hail'],
 'hall': ['haul'],
 'halve': ['have'],
 'handsome': ['hansom'],
 'hangar': ['hanger'],
 'hanger': ['hangar'],
 'hansom': ['handsome'],
 'hare': ['hair'],
 'harrier': ['hairier'],
 'hart': ['heart'],
 'has not': ["hasn't"],
 "hasn't": ['has not'],
 'haul': ['hall'],
 'have': ['halve'],
 'have not': ["haven't"],
 "haven't": ['have not'],
 'haw': ['hoar', 'whore'],
 'hay': ['hey'],
 'he had': ['he would', "he'd", 'heed'],
 'he has': ['he is', "he's"],
 'he is': ['he has', "he's"],
 'he shall': ['he will', "he'll", 'heal', 'heel'],
 'he will': ['he shall', "he'll", 'heal', 'heel'],
 'he would': ['he had', "he'd", 'heed'],
 "he'd": ['he had', 'he would', 'heed'],
 "he'll": ['he shall', 'he will', 'heal', 'heel'],
 "he's": ['he has', 'he is'],
 'heal': ['he shall', 'he will', "he'll", 'heel'],
 'hear': ['here'],
 'heard': ['herd'],
 'heart': ['hart'],
 'heed': ['he had', 'he would', "he'd"],
 'heel': ['he shall', 'he will', "he'll", 'heal'],
 'heir': ['air', 'ere'],
 'herd': ['heard'],
 'here': ['hear'],
 'heroin': ['heroine'],
 'heroine': ['heroin'],
 'hew': ['hue'],
 'hey': ['hay'],
 'hi': ['high'],
 'high': ['hi'],
 'higher': ['hire'],
 'him': ['hymn'],
 'hire': ['higher'],
 'ho': ['hoe'],
 'hoar': ['haw', 'whore'],
 'hoard': ['horde'],
 'hoarse': ['horse'],
 'hoe': ['ho'],
 'hoes': ['hose'],
 'hole': ['whole'],
 'holey': ['holy', 'wholly'],
 'holy': ['holey', 'wholly'],
 'hoop': ['whoop'],
 'horde': ['hoard'],
 'horse': ['hoarse'],
 'hose': ['hoes'],
 'hostel': ['hostile'],
 'hostile': ['hostel'],
 'hour': ['our'],
 'how are': ["how're"],
 'how did': ['how would', "how'd"],
 'how does': ['how has', 'how is', "how's"],
 'how has': ['how does', 'how is', "how's"],
 'how is': ['how does', 'how has', "how's"],
 'how will': ["how'll"],
 'how would': ['how did', "how'd"],
 "how'd": ['how did', 'how would'],
 "how'll": ['how will'],
 "how're": ['how are'],
 "how's": ['how does', 'how has', 'how is'],
 'hue': ['hew'],
 'humerus': ['humorous'],
 'humorous': ['humerus'],
 'hurdle': ['hurtle'],
 'hurtle': ['hurdle'],
 'hymn': ['him'],
 'hypercritical': ['hypocritical'],
 'hypocritical': ['hypercritical'],
 'i': ['aye', 'eye'],
 'i am': ["i'm"],
 'i had': ['i would', "i'd"],
 'i have': ["i've"],
 'i shall': ['aisle', 'i will', "i'll", 'isle'],
 'i will': ['aisle', 'i shall', "i'll", 'isle'],
 'i would': ['i had', "i'd"],
 "i'd": ['i had', 'i would'],
 "i'll": ['aisle', 'i shall', 'i will', 'isle'],
 "i'm": ['i am'],
 "i've": ['i have'],
 'idle': ['idol', 'idyll'],
 'idol': ['idle', 'idyll'],
 'idyll': ['idle', 'idol'],
 'illicit': ['elicit'],
 'illusion': ['allusion'],
 'imminent': ['eminent'],
 'in': ['an', 'and', 'end', 'inn'],
 'incidence': ['incidents'],
 'incidents': ['incidence'],
 'incite': ['insight'],
 'incredible': ['incredulous'],
 'incredulous': ['incredible'],
 'indict': ['indite'],
 'indite': ['indict'],
 'inequity': ['iniquity'],
 'ingenious': ['ingenuous'],
 'ingenuous': ['ingenious'],
 'iniquity': ['inequity'],
 'inn': ['an', 'and', 'end', 'in'],
 'insight': ['incite'],
 'intense': ['intents'],
 'intents': ['intense'],
 'interstate': ['intrastate'],
 'intrastate': ['interstate'],
 'is not': ["isn't"],
 'isle': ['aisle', 'i shall', 'i will', "i'll"],
 'islet': ['eyelet'],
 "isn't": ['is not'],
 'it has': ['it is', "it's", 'its'],
 'it is': ['it has', "it's", 'its'],
 'it shall': ['it will', "it'll"],
 'it will': ['it shall', "it'll"],
 'it would': ["it'd"],
 "it'd": ['it would'],
 "it'll": ['it shall', 'it will'],
 "it's": ['it has', 'it is', 'its'],
 'its': ['it has', 'it is', "it's"],
 'jalousie': ['jealousy'],
 'jam': ['jamb'],
 'jamb': ['jam'],
 'jealousy': ['jalousie'],
 'jean': ['gene'],
 'jeans': ['genes'],
 'jell': ['gel'],
 'jest': ['gist'],
 'jewel': ['joule'],
 'jibe': ['gibe'],
 'joule': ['jewel'],
 'judicial': ['judicious'],
 'judicious': ['judicial'],
 'kerb': ['curb'],
 'kernel': ['colonel'],
 'key': ['quay'],
 'kill': ['kiln'],
 'kiln': ['kill'],
 'knave': ['nave'],
 'knead': ['kneed', 'need'],
 'kneed': ['knead', 'need'],
 'knew': ['gnu', 'new'],
 'knight': ['night'],
 'knit': ['nit'],
 'knob': ['nob'],
 'knock': ['nock'],
 'knot': ['not'],
 'know': ['no'],
 'knows': ['nose'],
 'kohl': ['coal'],
 'kyu': ['cue', 'queue'],
 'laager': ['lager'],
 'lac': ['lack'],
 'lack': ['lac'],
 'lacks': ['lax'],
 'lade': ['laid'],
 'lager': ['laager'],
 'laid': ['lade'],
 'lain': ['lane'],
 'lam': ['lamb'],
 'lama': ['llama'],
 'lamb': ['lam'],
 'lane': ['lain'],
 'laps': ['lapse'],
 'lapse': ['laps'],
 'larva': ['lava'],
 'lase': ['laze'],
 'lava': ['larva'],
 'law': ['lore'],
 'lax': ['lacks'],
 'lay': ['lei', 'ley'],
 'laze': ['lase'],
 'lea': ['lee'],
 'leach': ['leech'],
 'lead': ['led'],
 'leak': ['leek'],
 'lean': ['lien'],
 'leased': ['least'],
 'least': ['leased'],
 'led': ['lead'],
 'lee': ['lea'],
 'leech': ['leach'],
 'leek': ['leak'],
 'lei': ['lay', 'ley'],
 'lessen': ['lesson'],
 'lesser': ['lessor'],
 'lesson': ['lessen'],
 'lessor': ['lesser'],
 'let us': ["let's"],
 "let's": ['let us'],
 'levee': ['levy'],
 'levy': ['levee'],
 'ley': ['lay', 'lei'],
 'liable': ['libel'],
 'liar': ['lyre'],
 'libel': ['liable'],
 'licence': ['license'],
 'license': ['licence'],
 'lichen': ['liken'],
 'licker': ['liquor'],
 'lie': ['lye'],
 'lien': ['lean'],
 'lieu': ['loo'],
 'liken': ['lichen'],
 'links': ['lynx'],
 'liquor': ['licker'],
 'literal': ['littoral'],
 'littoral': ['literal'],
 'llama': ['lama'],
 'lo': ['low'],
 'load': ['lode'],
 'loan': ['lone'],
 'locks': ['lox'],
 'lode': ['load'],
 'lone': ['loan'],
 'loo': ['lieu'],
 'loop': ['loupe'],
 'loot': ['lute'],
 'lore': ['law'],
 'loupe': ['loop'],
 'low': ['lo'],
 'lox': ['locks'],
 'lute': ['loot'],
 'lye': ['lie'],
 'lynx': ['links'],
 'lyre': ['liar'],
 "ma'am": ['madam'],
 'macintosh': ['mackintosh', 'mcintosh'],
 'mackintosh': ['macintosh', 'mcintosh'],
 'madam': ["ma'am"],
 'made': ['maid'],
 'magnate': ['magnet'],
 'magnet': ['magnate'],
 'magnificent': ['munificent'],
 'maid': ['made'],
 'mail': ['male'],
 'main': ['mane'],
 'maize': ['maze'],
 'male': ['mail'],
 'mall': ['maul'],
 'mane': ['main'],
 'manikin': ['mannequin'],
 'manna': ['manner', 'manor'],
 'mannequin': ['manikin'],
 'manner': ['manna', 'manor'],
 'manor': ['manna', 'manner'],
 'mantel': ['mantle'],
 'mantle': ['mantel'],
 'mare': ['mayor'],
 'marital': ['marshal', 'marshall', 'martial'],
 'mark': ['marque'],
 'marque': ['mark'],
 'marry': ['material', 'materiel', 'merry'],
 'marshal': ['marital', 'marshall', 'martial'],
 'marshall': ['marital', 'marshal', 'martial'],
 'marten': ['martian', 'martin'],
 'martial': ['marital', 'marshal', 'marshall'],
 'martian': ['marten', 'martin'],
 'martin': ['marten', 'martian'],
 'mask': ['masque'],
 'masque': ['mask'],
 'massed': ['mast'],
 'mast': ['massed'],
 'material': ['marry', 'materiel', 'merry'],
 'materiel': ['marry', 'material', 'merry'],
 'maul': ['mall'],
 'maw': ['moor', 'more'],
 'mayor': ['mare'],
 'maze': ['maize'],
 'mcintosh': ['macintosh', 'mackintosh'],
 'me': ['mi'],
 'mean': ['mien'],
 'meat': ['meet', 'mete'],
 'medal': ['meddle', 'metal', 'mettle'],
 'meddle': ['medal', 'metal', 'mettle'],
 'median': ['average', 'normal'],
 'meet': ['meat', 'mete'],
 'merry': ['marry', 'material', 'materiel'],
 'metal': ['medal', 'meddle', 'mettle'],
 'mete': ['meat', 'meet'],
 'meter': ['metre'],
 'metre': ['meter'],
 'mettle': ['medal', 'meddle', 'metal'],
 'mewl': ['mule'],
 'mews': ['muse'],
 'mi': ['me'],
 'mien': ['mean'],
 'might': ['mite'],
 'might have': ["might've"],
 "might've": ['might have'],
 'mil': ['mill'],
 'mill': ['mil'],
 'millinary': ['millinery'],
 'millinery': ['millinary'],
 'mince': ['mints'],
 'mind': ['mined'],
 'mined': ['mind'],
 'miner': ['minor', 'mynah'],
 'minor': ['miner', 'mynah'],
 'mints': ['mince'],
 'missal': ['missile'],
 'missed': ['mist'],
 'missile': ['missal'],
 'mist': ['missed'],
 'mite': ['might'],
 'moan': ['mown'],
 'moat': ['mote'],
 'mode': ['mowed'],
 'moor': ['maw', 'more'],
 'moose': ['mousse'],
 'more': ['maw', 'moor'],
 'morn': ['mourn'],
 'morning': ['mourning'],
 'mote': ['moat'],
 'mourn': ['morn'],
 'mourning': ['morning'],
 'mousse': ['moose'],
 'mouton': ['mutton'],
 'mowed': ['mode'],
 'mown': ['moan'],
 'mule': ['mewl'],
 'munificent': ['magnificent'],
 'muscle': ['mussel', 'muzzle'],
 'muse': ['mews'],
 'mussel': ['muscle', 'muzzle'],
 'must have': ["must've"],
 'must not': ["mustn't"],
 "must've": ['must have'],
 'mustard': ['mustered'],
 'mustered': ['mustard'],
 "mustn't": ['must not'],
 'mutton': ['mouton'],
 'muzzle': ['muscle', 'mussel'],
 'mynah': ['miner', 'minor'],
 'naval': ['navel'],
 'nave': ['knave'],
 'navel': ['naval'],
 'naw': ['gnaw', 'nor'],
 'nay': ['neigh'],
 'need': ['knead', 'kneed'],
 'need not': ["needn't"],
 "needn't": ['need not'],
 'neigh': ['nay'],
 'new': ['gnu', 'knew'],
 'nice': ['gneiss'],
 'nicks': ['nix'],
 'nigh': ['nye'],
 'night': ['knight'],
 'nine': ['9'],
 'nineteen': ['19'],
 'ninety': ['90'],
 'ninety-eight': ['98'],
 'ninety-five': ['95'],
 'ninety-four': ['94'],
 'ninety-nine': ['99'],
 'ninety-one': ['91'],
 'ninety-seven': ['97'],
 'ninety-six': ['96'],
 'ninety-three': ['93'],
 'ninety-two': ['92'],
 'nit': ['knit'],
 'nix': ['nicks'],
 'no': ['know'],
 'nob': ['knob'],
 'nock': ['knock'],
 'node': ['note'],
 'none': ['nun'],
 'nor': ['gnaw', 'naw'],
 'normal': ['average', 'median'],
 'nose': ['knows'],
 'not': ['knot'],
 'note': ['node'],
 'nun': ['none'],
 'nye': ['nigh'],
 'oar': ['awe', 'oh', 'or', 'ore', 'owe'],
 'od': ['odd'],
 'odd': ['od'],
 'ode': ['owed'],
 'official': ['officious'],
 'officious': ['official'],
 'oh': ['awe', 'oar', 'or', 'ore', 'owe'],
 'one': ['1', 'won'],
 'one hundred': ['100'],
 'or': ['awe', 'oar', 'oh', 'ore', 'owe'],
 'oracle': ['auricle'],
 'oral': ['aural'],
 'orc': ['auk'],
 'ore': ['awe', 'oar', 'oh', 'or', 'owe'],
 'oscillate': ['osculate'],
 'osculate': ['oscillate'],
 'ought': ['aught'],
 'our': ['hour'],
 'overdo': ['overdue'],
 'overdue': ['overdo'],
 'overseas': ['oversees'],
 'oversees': ['overseas'],
 'owe': ['awe', 'oar', 'oh', 'or', 'ore'],
 'owed': ['ode'],
 'paced': ['paste'],
 'packed': ['pact'],
 'packs': ['pax'],
 'pact': ['packed'],
 'paean': ['peon'],
 'pail': ['pale'],
 'pain': ['pane'],
 'pair': ['pare', 'pear'],
 'palate': ['palette', 'pallet'],
 'pale': ['pail'],
 'palette': ['palate', 'pallet'],
 'pall': ['pawl'],
 'pallet': ['palate', 'palette'],
 'paltry': ['poultry'],
 'pane': ['pain'],
 'parameter': ['perimeter'],
 'pare': ['pair', 'pear'],
 'parish': ['perish'],
 'pascal': ['paschal'],
 'paschal': ['pascal'],
 'passed': ['past'],
 'past': ['passed'],
 'paste': ['paced'],
 'paten': ['patten', 'pattern'],
 'patience': ['patients'],
 'patients': ['patience'],
 'patten': ['paten', 'pattern'],
 'pattern': ['paten', 'patten'],
 'paul': ['pole', 'poll', 'pull'],
 'pause': ['paws', 'pores', 'pours'],
 'pawl': ['pall'],
 'pawn': ['porn'],
 'paws': ['pause', 'pores', 'pours'],
 'pax': ['packs'],
 'pea': ['pee'],
 'peace': ['piece'],
 'peak': ['peek', 'peke', 'pique'],
 'peal': ['peel'],
 'pear': ['pair', 'pare'],
 'pearl': ['purl'],
 'pedal': ['peddle'],
 'peddle': ['pedal'],
 'pee': ['pea'],
 'peek': ['peak', 'peke', 'pique'],
 'peel': ['peal'],
 'peer': ['appear', 'pier', 'pure'],
 'peers': ['piers'],
 'peke': ['peak', 'peek', 'pique'],
 'peon': ['paean'],
 'peremptory': ['pre-emptory'],
 'perimeter': ['parameter'],
 'perish': ['parish'],
 'perquisite': ['prerequisite'],
 'persecute': ['prosecute'],
 'personal': ['personnel'],
 'personnel': ['personal'],
 'perspective': ['prospective'],
 'petit': ['petite', 'petty'],
 'petite': ['petit', 'petty'],
 'petty': ['petit', 'petite'],
 'phase': ['faze'],
 'phew': ['few'],
 'phi': ['fie'],
 'phial': ['file'],
 'phiz': ['fizz'],
 'phrase': ['frays'],
 'physic': ['physique', 'psychic'],
 'physique': ['physic', 'psychic'],
 'pi': ['pie'],
 'pica': ['pika'],
 'pie': ['pi'],
 'piece': ['peace'],
 'pier': ['appear', 'peer', 'pure'],
 'piers': ['peers'],
 'pika': ['pica'],
 'pique': ['peak', 'peek', 'peke'],
 'place': ['plaice'],
 'plaice': ['place'],
 'plain': ['plane'],
 'plait': ['plate'],
 'plane': ['plain'],
 'plate': ['plait'],
 'pleas': ['please'],
 'please': ['pleas'],
 'plum': ['plumb'],
 'plumb': ['plum'],
 'pole': ['paul', 'poll', 'pull'],
 'policy': ['polity'],
 'polity': ['policy'],
 'poll': ['paul', 'pole', 'pull'],
 'poof': ['pouffe'],
 'poor': ['pore', 'pour'],
 'poplar': ['popular'],
 'populace': ['populous'],
 'popular': ['poplar'],
 'populous': ['populace'],
 'pore': ['poor', 'pour'],
 'pores': ['pause', 'paws', 'pours'],
 'porn': ['pawn'],
 'pouffe': ['poof'],
 'poultry': ['paltry'],
 'pour': ['poor', 'pore'],
 'pours': ['pause', 'paws', 'pores'],
 'practice': ['practise'],
 'practise': ['practice'],
 'praise': ['prays', 'preys'],
 'pray': ['prey'],
 'prays': ['praise', 'preys'],
 'pre-emptory': ['peremptory'],
 'precede': ['proceed'],
 'prerequisite': ['perquisite'],
 'prescribe': ['proscribe'],
 'presence': ['presents'],
 'presentiment': ['presentment'],
 'presentment': ['presentiment'],
 'presents': ['presence'],
 'prey': ['pray'],
 'preys': ['praise', 'prays'],
 'pride': ['pried'],
 'pried': ['pride'],
 'pries': ['prize'],
 'primer': ['primmer'],
 'primmer': ['primer'],
 'prince': ['prints'],
 'principal': ['principle'],
 'principle': ['principal'],
 'prints': ['prince'],
 'prize': ['pries'],
 'proceed': ['precede'],
 'profit': ['prophet'],
 'prone': ['supine'],
 'prophecy': ['prophesy'],
 'prophesy': ['prophecy'],
 'prophet': ['profit'],
 'propose': ['purpose'],
 'proscribe': ['prescribe'],
 'prosecute': ['persecute'],
 'prospective': ['perspective'],
 'prostate': ['prostrate'],
 'prostrate': ['prostate'],
 'psychic': ['physic', 'physique'],
 'pull': ['paul', 'pole', 'poll'],
 'pure': ['appear', 'peer', 'pier'],
 'purl': ['pearl'],
 'purpose': ['propose'],
 'put': ['putt'],
 'putt': ['put'],
 'quarts': ['quartz'],
 'quartz': ['quarts'],
 'quay': ['key'],
 'quean': ['queen'],
 'queen': ['quean'],
 'queue': ['cue', 'kyu'],
 'quire': ['choir'],
 'r': ['are'],
 'rabbet': ['rabbit'],
 'rabbit': ['rabbet'],
 'rack': ['wrack'],
 'rain': ['reign', 'rein'],
 'raise': ['rays', 'raze'],
 'rap': ['rapped', 'rapt', 'wrap', 'wrapped'],
 'rapped': ['rap', 'rapt', 'wrap', 'wrapped'],
 'rapper': ['wrapper'],
 'rapt': ['rap', 'rapped', 'wrap', 'wrapped'],
 'rate': ['right', 'rite', 'wright', 'write'],
 'raw': ['roar'],
 'rays': ['raise', 'raze'],
 'raze': ['raise', 'rays'],
 'read': ['red', 'reed'],
 'real': ['reel'],
 'reality': ['realty'],
 'realty': ['reality'],
 'red': ['read', 'reed'],
 'reed': ['read', 'red'],
 'reek': ['wreak'],
 'reel': ['real'],
 'register': ['registrar'],
 'registrar': ['register'],
 'reign': ['rain', 'rein'],
 'rein': ['rain', 'reign'],
 'reluctant': ['reticent'],
 'residence': ['residents'],
 'residents': ['residence'],
 'rest': ['rust', 'wrest'],
 'retch': ['wretch'],
 'reticent': ['reluctant'],
 'review': ['revue'],
 'revue': ['review'],
 'rheum': ['room'],
 'rho': ['roe', 'row'],
 'riffle': ['rifle'],
 'rifle': ['riffle'],
 'rigger': ['rigor'],
 'right': ['rate', 'rite', 'wright', 'write'],
 'rigor': ['rigger'],
 'ring': ['wring'],
 'rite': ['rate', 'right', 'wright', 'write'],
 'road': ['rode', 'rowed'],
 'roar': ['raw'],
 'rode': ['road', 'rowed'],
 'roe': ['rho', 'row'],
 'roil': ['royal'],
 'role': ['roll'],
 'roll': ['role'],
 'roo': ['roux', 'rue'],
 'rood': ['rude', 'rued'],
 'room': ['rheum'],
 'roomer': ['rumour'],
 'root': ['route'],
 'rose': ['rouse', 'rows'],
 'rota': ['rotor'],
 'rote': ['wrote'],
 'rotor': ['rota'],
 'rough': ['ruff'],
 'rouse': ['rose', 'rows'],
 'route': ['root'],
 'roux': ['roo', 'rue'],
 'row': ['rho', 'roe'],
 'rowed': ['road', 'rode'],
 'rows': ['rose', 'rouse'],
 'royal': ['roil'],
 'rude': ['rood', 'rued'],
 'rue': ['roo', 'roux'],
 'rued': ['rood', 'rude'],
 'ruff': ['rough'],
 'ruin': ['rune'],
 'rumour': ['roomer'],
 'rune': ['ruin'],
 'rung': ['wrung'],
 'rust': ['rest', 'wrest'],
 'rye': ['wry'],
 'sac': ['sack'],
 'sachet': ['sashay'],
 'sack': ['sac'],
 'sail': ['sale'],
 'sale': ['sail'],
 'sane': ['seine'],
 'sanitarium': ['sanitorium'],
 'sanitorium': ['sanitarium'],
 'sashay': ['sachet'],
 'satire': ['satyr'],
 'satyr': ['satire'],
 'sauce': ['source'],
 'saver': ['savour'],
 'savour': ['saver'],
 'saw': ['sew', 'so', 'soar', 'sore', 'sow'],
 'scene': ['seen'],
 'scent': ['cent', 'sent'],
 'scull': ['skull'],
 'sea': ['see'],
 'sealing': ['ceiling'],
 'seam': ['seem'],
 'seaman': ['semen'],
 'sear': ['seer', 'sere'],
 'seas': ['sees', 'seize'],
 'see': ['sea'],
 'seed': ['cede'],
 'seem': ['seam'],
 'seen': ['scene'],
 'seer': ['sear', 'sere'],
 'sees': ['seas', 'seize'],
 'seine': ['sane'],
 'seize': ['seas', 'sees'],
 'sell': ['cell'],
 'seller': ['cellar'],
 'semen': ['seaman'],
 'sense': ['census'],
 'sensor': ['censer', 'censor', 'censure'],
 'sent': ['cent', 'scent'],
 'sere': ['sear', 'seer'],
 'serf': ['surf'],
 'serge': ['surge'],
 'serial': ['cereal'],
 'session': ['cession'],
 'seven': ['7'],
 'seventeen': ['17'],
 'seventy': ['70'],
 'seventy-eight': ['78'],
 'seventy-five': ['75'],
 'seventy-four': ['74'],
 'seventy-nine': ['79'],
 'seventy-one': ['71'],
 'seventy-seven': ['77'],
 'seventy-six': ['76'],
 'seventy-three': ['73'],
 'seventy-two': ['72'],
 'sew': ['saw', 'so', 'soar', 'sore', 'sow'],
 'shake': ['sheikh'],
 'shanty': ['chantey'],
 'she had': ['she would', "she'd"],
 'she has': ['she is', "she's"],
 'she is': ['she has', "she's"],
 'she shall': ['she will', "she'll"],
 'she will': ['she shall', "she'll"],
 'she would': ['she had', "she'd"],
 "she'd": ['she had', 'she would'],
 "she'll": ['she shall', 'she will'],
 "she's": ['she has', 'she is'],
 'shear': ['shearn', 'sheer'],
 'shearn': ['shear', 'sheer'],
 'sheer': ['shear', 'shearn'],
 'sheik': ['chic'],
 'sheikh': ['shake'],
 'shoe': ['shoo'],
 'shone': ['shown'],
 'shoo': ['shoe'],
 'shoot': ['chute'],
 'should have': ["should've"],
 'should not': ["shouldn't"],
 "should've": ['should have'],
 "shouldn't": ['should not'],
 'shown': ['shone'],
 'sic': ['sick'],
 'sick': ['sic'],
 'side': ['sighed'],
 'sighed': ['side'],
 'sighs': ['size'],
 'sight': ['cite', 'site'],
 'sign': ['sine'],
 'signet': ['cygnet'],
 'sine': ['sign'],
 'sink': ['sync', 'synch'],
 'site': ['cite', 'sight'],
 'six': ['6'],
 'sixteen': ['16'],
 'sixty': ['60'],
 'sixty-eight': ['68'],
 'sixty-five': ['65'],
 'sixty-four': ['64'],
 'sixty-nine': ['69'],
 'sixty-one': ['61'],
 'sixty-seven': ['67'],
 'sixty-six': ['66'],
 'sixty-three': ['63'],
 'sixty-two': ['62'],
 'size': ['sighs'],
 'skull': ['scull'],
 'slay': ['sleigh'],
 'sleigh': ['slay'],
 'sleight': ['slight'],
 'slight': ['sleight'],
 'sloe': ['slow'],
 'slow': ['sloe'],
 'so': ['saw', 'sew', 'soar', 'sore', 'sow'],
 'soar': ['saw', 'sew', 'so', 'sore', 'sow'],
 'soared': ['sward', 'sword'],
 'sol': ['sole', 'soul'],
 'sold': ['soled'],
 'sole': ['sol', 'soul'],
 'soled': ['sold'],
 'some': ['sum'],
 'somebody has': ['somebody is', "somebody's"],
 'somebody is': ['somebody has', "somebody's"],
 "somebody's": ['somebody has', 'somebody is'],
 'someone has': ['someone is', "someone's"],
 'someone is': ['someone has', "someone's"],
 "someone's": ['someone has', 'someone is'],
 'something has': ['something is', "something's"],
 'something is': ['something has', "something's"],
 "something's": ['something has', 'something is'],
 'son': ['sun'],
 'sore': ['saw', 'sew', 'so', 'soar', 'sow'],
 'sort': ['sought'],
 'sought': ['sort'],
 'soul': ['sol', 'sole'],
 'source': ['sauce'],
 'sow': ['saw', 'sew', 'so', 'soar', 'sore'],
 'spa': ['spar'],
 'spade': ['spayed'],
 'spar': ['spa'],
 'spayed': ['spade'],
 'spoor': ['spore'],
 'spore': ['spoor'],
 'staid': ['stayed'],
 'stair': ['stare'],
 'stairs': ['stares'],
 'stake': ['steak'],
 'stalk': ['stork'],
 'stare': ['stair'],
 'stares': ['stairs'],
 'stationary': ['stationery'],
 'stationery': ['stationary'],
 'stayed': ['staid'],
 'steak': ['stake'],
 'steal': ['steel'],
 'steel': ['steal'],
 'step': ['steppe'],
 'steppe': ['step'],
 'stile': ['sty', 'style'],
 'storey': ['story'],
 'stork': ['stalk'],
 'story': ['storey'],
 'straight': ['strait'],
 'strait': ['straight'],
 'sty': ['stile', 'style'],
 'style': ['stile', 'sty'],
 'succour': ['sucker'],
 'sucker': ['succour'],
 'suit': ['suite', 'sweet'],
 'suite': ['suit', 'sweet'],
 'sum': ['some'],
 'summary': ['summery'],
 'summery': ['summary'],
 'sun': ['son'],
 'supine': ['prone'],
 'surf': ['serf'],
 'surge': ['serge'],
 'sward': ['soared', 'sword'],
 'swat': ['swot'],
 'sweet': ['suit', 'suite'],
 'sword': ['soared', 'sward'],
 'swot': ['swat'],
 'symbol': ['cymbal', 'cymbol'],
 'sync': ['sink', 'synch'],
 'synch': ['sink', 'sync'],
 'tacet': ['tacit'],
 'tacit': ['tacet'],
 'tacked': ['tact'],
 'tacks': ['tax'],
 'tact': ['tacked'],
 'tail': ['tale'],
 'take': ['bring'],
 'tale': ['tail'],
 'talesman': ['talisman'],
 'talisman': ['talesman'],
 'talk': ['torque'],
 'taper': ['tapir'],
 'tapir': ['taper'],
 'tare': ['tear', 'tier'],
 'tasteful': ['tasty'],
 'tasty': ['tasteful'],
 'taught': ['taut', 'tort'],
 'taupe': ['tope'],
 'taut': ['taught', 'tort'],
 'tax': ['tacks'],
 'te': ['tea', 'tee'],
 'tea': ['te', 'tee'],
 'team': ['teem'],
 'tear': ['tare', 'tier'],
 'teas': ['tease'],
 'tease': ['teas'],
 'tee': ['te', 'tea'],
 'teem': ['team'],
 'ten': ['10'],
 'tense': ['tents'],
 'tents': ['tense'],
 'terce': ['terse'],
 'tern': ['turn'],
 'terse': ['terce'],
 'than': ['then'],
 'that are': ["that're"],
 'that had': ['that would', "that'd"],
 'that has': ['that is', "that's"],
 'that is': ['that has', "that's"],
 'that shall': ['that will', "that'll"],
 'that will': ['that shall', "that'll"],
 'that would': ['that had', "that'd"],
 "that'd": ['that had', 'that would'],
 "that'll": ['that shall', 'that will'],
 "that're": ['that are'],
 "that's": ['that has', 'that is'],
 'their': ['there', 'they are', 'they were', "they're"],
 'then': ['than'],
 'there': ['their', 'they are', 'they were', "they're"],
 'there are': ["there're"],
 'there had': ['there would', "there'd"],
 'there has': ['there is', "there's"],
 'there is': ['there has', "there's"],
 'there shall': ['there will', "there'll"],
 'there will': ['there shall', "there'll"],
 'there would': ['there had', "there'd"],
 "there'd": ['there had', 'there would'],
 "there'll": ['there shall', 'there will'],
 "there're": ['there are'],
 "there's": ['there has', 'there is'],
 'they are': ['their', 'there', 'they were', "they're"],
 'they had': ['they would', "they'd"],
 'they have': ["they've"],
 'they shall': ['they will', "they'll"],
 'they were': ['their', 'there', 'they are', "they're"],
 'they will': ['they shall', "they'll"],
 'they would': ['they had', "they'd"],
 "they'd": ['they had', 'they would'],
 "they'll": ['they shall', 'they will'],
 "they're": ['their', 'there', 'they are', 'they were'],
 "they've": ['they have'],
 'thirteen': ['13'],
 'thirty': ['30'],
 'thirty-eight': ['38'],
 'thirty-five': ['35'],
 'thirty-four': ['34'],
 'thirty-nine': ['39'],
 'thirty-one': ['31'],
 'thirty-seven': ['37'],
 'thirty-six': ['36'],
 'thirty-three': ['33'],
 'thirty-two': ['32'],
 'this has': ['this is', "this's"],
 'this is': ['this has', "this's"],
 "this's": ['this has', 'this is'],
 'those are': ["those're"],
 'those have': ["those've"],
 "those're": ['those are'],
 "those've": ['those have'],
 'three': ['3'],
 'threw': ['through'],
 'throe': ['throw'],
 'throes': ['throws'],
 'throne': ['thrown'],
 'through': ['threw'],
 'throw': ['throe'],
 'thrown': ['throne'],
 'throws': ['throes'],
 'thyme': ['time'],
 'tic': ['tick'],
 'tick': ['tic'],
 'tide': ['tied'],
 'tied': ['tide'],
 'tier': ['tare', 'tear'],
 'time': ['thyme'],
 'tire': ['tyre'],
 'to': ['2', 'toe', 'too', 'tow', 'two'],
 'toad': ['toed', 'towed'],
 'tocsin': ['toxin'],
 'toe': ['2', 'to', 'too', 'tow', 'two'],
 'toed': ['toad', 'towed'],
 'told': ['tolled'],
 'tole': ['toll'],
 'toll': ['tole'],
 'tolled': ['told'],
 'ton': ['tun'],
 'too': ['2', 'to', 'toe', 'tow', 'two'],
 'tool': ['tulle'],
 'tope': ['taupe'],
 'tor': ['tore'],
 'tore': ['tor'],
 'torque': ['talk'],
 'tort': ['taught', 'taut'],
 'tortuous': ['torturous'],
 'torturous': ['tortuous'],
 'tough': ['tuff'],
 'tow': ['2', 'to', 'toe', 'too', 'two'],
 'towed': ['toad', 'toed'],
 'toxin': ['tocsin'],
 'track': ['tracked', 'tract'],
 'tracked': ['track', 'tract'],
 'tract': ['track', 'tracked'],
 'tray': ['trey'],
 'trey': ['tray'],
 'troop': ['troupe'],
 'troupe': ['troop'],
 'trussed': ['trust'],
 'trust': ['trussed'],
 'trustee': ['trusty'],
 'trusty': ['trustee'],
 'trying': ['drying'],
 'tuba': ['tuber'],
 'tuber': ['tuba'],
 'tuff': ['tough'],
 'tulle': ['tool'],
 'tun': ['ton'],
 'turban': ['turbine'],
 'turbine': ['turban'],
 'turn': ['tern'],
 'twelve': ['12'],
 'twenty': ['20'],
 'twenty-eight': ['28'],
 'twenty-five': ['25'],
 'twenty-four': ['24'],
 'twenty-nine': ['29'],
 'twenty-one': ['21'],
 'twenty-seven': ['27'],
 'twenty-six': ['26'],
 'twenty-three': ['23'],
 'twenty-two': ['22'],
 'two': ['2', 'to', 'toe', 'too', 'tow'],
 'tyre': ['tire'],
 'undo': ['undue'],
 'undue': ['undo'],
 'up': ['upped'],
 'upped': ['up'],
 'urn': ['earn'],
 'use': ['ewes', 'yews'],
 'vain': ['vane', 'vein'],
 'valance': ['valence'],
 'vale': ['veil'],
 'valence': ['valance'],
 'vane': ['vain', 'vein'],
 'vary': ['very'],
 'vat': ['fat'],
 'veil': ['vale'],
 'vein': ['vain', 'vane'],
 'veracious': ['voracious'],
 'very': ['vary'],
 'vial': ['vile', 'viol'],
 'vice': ['vise'],
 'vicious': ['viscous', 'viscus'],
 'vile': ['vial', 'viol'],
 'villain': ['villein'],
 'villein': ['villain'],
 'viol': ['vial', 'vile'],
 'virtu': ['virtue'],
 'virtue': ['virtu'],
 'viscous': ['vicious', 'viscus'],
 'viscus': ['vicious', 'viscous'],
 'vise': ['vice'],
 'voracious': ['veracious'],
 'wade': ['weighed'],
 'wail': ['wale', 'whale'],
 'wain': ['wane'],
 'waist': ['waste'],
 'wait': ['weight'],
 'waive': ['wave'],
 'wale': ['wail', 'whale'],
 'wall': ['waul'],
 'wane': ['wain'],
 'wanna': ['want to'],
 'want': ['wont'],
 'want to': ['wanna'],
 'war': ['wore'],
 'ware': ['wear', 'where'],
 'wares': ['wears'],
 'warn': ['worn'],
 'wart': ['wort'],
 'was not': ["wasn't"],
 "wasn't": ['was not'],
 'waste': ['waist'],
 'watt': ['what'],
 'waul': ['wall'],
 'wave': ['waive'],
 'wax': ['whacks'],
 'way': ['weigh', 'whey'],
 'we': ['wee', 'whee'],
 'we are': ["we're", 'weir'],
 'we did': ['we had', 'we would', "we'd", 'weed'],
 'we had': ['we did', 'we would', "we'd", 'weed'],
 'we have': ["we've"],
 'we shall': ['we will',
              "we'll",
              'weal',
              'well',
              'wheel',
              'while',
              'wile',
              'will'],
 'we will': ['we shall',
             "we'll",
             'weal',
             'well',
             'wheel',
             'while',
             'wile',
             'will'],
 'we would': ['we did', 'we had', "we'd", 'weed'],
 'we would have': ["we'd've"],
 "we'd": ['we did', 'we had', 'we would', 'weed'],
 "we'd've": ['we would have'],
 "we'll": ['we shall',
           'we will',
           'weal',
           'well',
           'wheel',
           'while',
           'wile',
           'will'],
 "we're": ['we are', 'weir'],
 "we've": ['we have'],
 'weak': ['week'],
 'weal': ['we shall',
          'we will',
          "we'll",
          'well',
          'wheel',
          'while',
          'wile',
          'will'],
 'wean': ['ween'],
 'wear': ['ware', 'where'],
 'wears': ['wares'],
 'weather': ['wether', 'whether'],
 'weaver': ['weever'],
 'wee': ['we', 'whee'],
 'weed': ['we did', 'we had', 'we would', "we'd"],
 'week': ['weak'],
 'ween': ['wean'],
 'weever': ['weaver'],
 'weigh': ['way', 'whey'],
 'weighed': ['wade'],
 'weight': ['wait'],
 'weir': ['we are', "we're"],
 'well': ['we shall',
          'we will',
          "we'll",
          'weal',
          'wheel',
          'while',
          'wile',
          'will'],
 'were': ['whirr'],
 'were not': ["weren't"],
 "weren't": ['were not'],
 'wet': ['whet'],
 'wether': ['weather', 'whether'],
 'whacks': ['wax'],
 'whale': ['wail', 'wale'],
 'what': ['watt'],
 'what are': ['what were', "what're"],
 'what did': ["what'd"],
 'what does': ['what has', 'what is', "what's"],
 'what has': ['what does', 'what is', "what's"],
 'what have': ["what've"],
 'what is': ['what does', 'what has', "what's"],
 'what shall': ['what will', "what'll"],
 'what were': ['what are', "what're"],
 'what will': ['what shall', "what'll"],
 "what'd": ['what did'],
 "what'll": ['what shall', 'what will'],
 "what're": ['what are', 'what were'],
 "what's": ['what does', 'what has', 'what is'],
 "what've": ['what have'],
 'wheald': ['wheeled'],
 'whee': ['we', 'wee'],
 'wheel': ['we shall',
           'we will',
           "we'll",
           'weal',
           'well',
           'while',
           'wile',
           'will'],
 'wheeled': ['wheald'],
 'when has': ['when is', "when's"],
 'when is': ['when has', "when's"],
 "when's": ['when has', 'when is'],
 'where': ['ware', 'wear'],
 'where are': ["where're"],
 'where did': ["where'd"],
 'where does': ['where has', 'where is', "where's"],
 'where has': ['where does', 'where is', "where's"],
 'where have': ["where've"],
 'where is': ['where does', 'where has', "where's"],
 'where shall': ['where will', "where'll"],
 'where will': ['where shall', "where'll"],
 "where'd": ['where did'],
 "where'll": ['where shall', 'where will'],
 "where're": ['where are'],
 "where's": ['where does', 'where has', 'where is'],
 "where've": ['where have'],
 'whet': ['wet'],
 'whether': ['weather', 'wether'],
 'whey': ['way', 'weigh'],
 'which': ['witch'],
 'which are': ["which're"],
 'which had': ['which would', "which'd"],
 'which has': ['which is', "which's"],
 'which have': ["which've"],
 'which is': ['which has', "which's"],
 'which shall': ['which will', "which'll"],
 'which will': ['which shall', "which'll"],
 'which would': ['which had', "which'd"],
 "which'd": ['which had', 'which would'],
 "which'll": ['which shall', 'which will'],
 "which're": ['which are'],
 "which's": ['which has', 'which is'],
 "which've": ['which have'],
 'whig': ['wig'],
 'while': ['we shall',
           'we will',
           "we'll",
           'weal',
           'well',
           'wheel',
           'wile',
           'will'],
 'whine': ['wine'],
 'whirl': ['whorl'],
 'whirled': ['world'],
 'whirr': ['were'],
 'whit': ['wit'],
 'white': ['wight'],
 'whither': ['wither'],
 'who are': ["who're"],
 'who did': ['who had', 'who would', "who'd"],
 'who does': ['who has', 'who is', "who''s", "who's", 'whose'],
 'who had': ['who did', 'who would', "who'd"],
 'who has': ['who does', 'who is', "who''s", "who's", 'whose'],
 'who have': ["who've"],
 'who is': ['who does', 'who has', "who''s", "who's", 'whose'],
 'who shall': ['who will', "who'll"],
 'who will': ['who shall', "who'll"],
 'who would': ['who did', 'who had', "who'd"],
 'who would have': ["who'd've"],
 "who''s": ['who does', 'who has', 'who is', "who's", 'whose'],
 "who'd": ['who did', 'who had', 'who would'],
 "who'd've": ['who would have'],
 "who'll": ['who shall', 'who will'],
 "who're": ['who are'],
 "who's": ['who does', 'who has', 'who is', "who''s", 'whose'],
 "who've": ['who have'],
 'whoa': ['woe'],
 'whole': ['hole'],
 'wholly': ['holey', 'holy'],
 'whoop': ['hoop'],
 'whore': ['haw', 'hoar'],
 'whorl': ['whirl'],
 'whose': ['who does', 'who has', 'who is', "who''s", "who's"],
 'why are': ["why're"],
 'why did': ["why'd"],
 'why does': ['why has', 'why is', "why's"],
 'why has': ['why does', 'why is', "why's"],
 'why is': ['why does', 'why has', "why's"],
 "why'd": ['why did'],
 "why're": ['why are'],
 "why's": ['why does', 'why has', 'why is'],
 'wig': ['whig'],
 'wight': ['white'],
 'wile': ['we shall',
          'we will',
          "we'll",
          'weal',
          'well',
          'wheel',
          'while',
          'will'],
 'will': ['we shall',
          'we will',
          "we'll",
          'weal',
          'well',
          'wheel',
          'while',
          'wile'],
 'will not': ["won't"],
 'will not (archaic)': ["willn't", 'wonnot'],
 "willn't": ['will not (archaic)', 'wonnot'],
 'wine': ['whine'],
 'wit': ['whit'],
 'witch': ['which'],
 'wither': ['whither'],
 'woe': ['whoa'],
 'won': ['1', 'one'],
 "won't": ['will not'],
 'wonnot': ['will not (archaic)', "willn't"],
 'wont': ['want'],
 'wood': ['would'],
 'wore': ['war'],
 'world': ['whirled'],
 'worn': ['warn'],
 'worst': ['wurst'],
 'wort': ['wart'],
 'would': ['wood'],
 'would have': ["would've"],
 'would not': ["wouldn't"],
 'would not have': ["wouldn't've"],
 "would've": ['would have'],
 "wouldn't": ['would not'],
 "wouldn't've": ['would not have'],
 'wrack': ['rack'],
 'wrap': ['rap', 'rapped', 'rapt', 'wrapped'],
 'wrapped': ['rap', 'rapped', 'rapt', 'wrap'],
 'wrapper': ['rapper'],
 'wreak': ['reek'],
 'wrest': ['rest', 'rust'],
 'wretch': ['retch'],
 'wright': ['rate', 'right', 'rite', 'write'],
 'wring': ['ring'],
 'write': ['rate', 'right', 'rite', 'wright'],
 'wrote': ['rote'],
 'wrung': ['rung'],
 'wry': ['rye'],
 'wurst': ['worst'],
 'yaw': ['yore', 'you are/ you are', "you''re", "you're", 'your'],
 'yew': ['ewe', 'you'],
 'yews': ['ewes', 'use'],
 'yoke': ['yolk'],
 'yolk': ['yoke'],
 'yore': ['yaw', 'you are/ you are', "you''re", "you're", 'your'],
 'you': ['ewe', 'yew'],
 'you are/ you are': ['yaw', 'yore', "you''re", "you're", 'your'],
 'you had': ['you would', "you'd"],
 'you have': ["you've"],
 'you shall': ['you will', "you'll", 'yule'],
 'you will': ['you shall', "you'll", 'yule'],
 'you would': ['you had', "you'd"],
 "you''re": ['yaw', 'yore', 'you are/ you are', "you're", 'your'],
 "you'd": ['you had', 'you would'],
 "you'll": ['you shall', 'you will', 'yule'],
 "you're": ['yaw', 'yore', 'you are/ you are', "you''re", 'your'],
 "you've": ['you have'],
 'your': ['yaw', 'yore', 'you are/ you are', "you''re", "you're"],
 'yule': ['you shall', 'you will', "you'll"],
 'zero': ['0']}