__name__ = "ratter"
__version__ = "0.1.0-a0"
__author__ = "Fabian Meyer"
__maintainer__ = "Fabian Meyer"
__email__ = "fabian.meyer@ise.fraunhofer.de"
__copyright__ = "Copyright 2020, Fraunhofer ISE"
__license__ = "BSD 3-clause"
__url__ = "https://github.com/fa-me/ratter"
__summary__ = """calculate coherent reflection, absorption
and transmission of thin layer stacks"""