
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-05-21T16:18:29-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "747e4d7ea3b34475a603e63fd49f30e4851c5c86",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
