import pyautogui
import json
import time
click_list= []

def autoclick(interval, carray="data.json"):
    """
    Interval: int value, specify how long you want to wait between click (in Seconds)
    Carray: Click-Array, the .json file that the click positions are in. By Default, it's data.json.
    This function clicks using the .json file generated by track.get_position().
    """
    try: 
        with open(carray, 'r') as infile:
            click_list = json.load(infile)
        print(click_list)
        x = [i[0] for i in click_list]
        y = [i[1] for i in click_list]
        for i in range(0,click_list.__len__()):
            pyautogui.click(x[i], y[i])
            time.sleep(interval)
    except FileNotFoundError:
        pass